"use client";
import {useState} from 'react';
import {ArrowUpRight,Download,RefreshCw} from 'lucide-react';
import {GmailCodes,AuthenticatorCodes} from './account-google-tools';
import {weeklyWindow,remaining,isLive,type QuotaProfile} from '@/lib/quota';
import {officialFieldStamp} from '@/lib/quota-evidence';
import {useAccountQueries,accountQueryLabel} from './use-account-queries';

export type DetailTab='plan'|'resets'|'history'|'mail'|'auth';
const stamp=(value?:string|number|null)=>value?new Date(typeof value==='number'?value*1000:value).toLocaleString('zh-CN',{timeZone:'Asia/Taipei',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}):'暂未提供';
const plan=(value?:string|null)=>value?({pro:'Pro',plus:'Plus',free:'Free',team:'Team',business:'Business',enterprise:'Enterprise'}[value]||value):'套餐待查询';
const percentage=(p:QuotaProfile,minutes:number)=>{const value=remaining(p.windows.find(w=>w.windowDurationMins===minutes));return value===null?'—':`${value}%`;};
function expiry(value:number|null,now:number,noExpiry?:boolean,dateLabel?:string){if(!value)return dateLabel?'具体到期时刻暂未提供':noExpiry?'无固定到期时间':'暂未提供';const minutes=Math.ceil((value*1000-now)/60000);return value*1000<=now?'已到期':`剩余 ${Math.floor(minutes/1440)} 天 ${Math.floor(minutes%1440/60)} 小时 ${minutes%60} 分钟`;}
type Props={email:string;profile?:QuotaProfile;history:QuotaProfile[];lastSeen?:string;total:number|null;currentEmail:string|null;now:number;tab:DetailTab;onTab:(value:DetailTab)=>void;onStatistics:()=>void;canManage:boolean;onRefresh:()=>void};
export default function AccountDetails({email,profile:storedProfile,history,lastSeen,total,currentEmail,now,tab,onTab,onStatistics,canManage,onRefresh}:Props){
  const [openingBilling,setOpeningBilling]=useState(false),[billingMessage,setBillingMessage]=useState(''),[billingError,setBillingError]=useState('');
  const autoQuery=useAccountQueries(canManage,onRefresh);
  const profile=storedProfile;
  async function queryQuota(){await autoQuery.request(email);}
  async function openBilling(){setOpeningBilling(true);setBillingMessage('');setBillingError('');try{const response=await fetch(`/api/local-apps/identity/open-billing?email=${encodeURIComponent(email)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),body=await response.json() as {error?:string;opened?:boolean;expectedEmail?:string;profileLabel?:string};if(!response.ok)throw new Error(body.error||'此账号的账单页面暂时无法打开。');if(body.opened!==true||body.expectedEmail!==email.toLowerCase())throw new Error('未能确认对应的 Chrome 个人资料，请重试。');setBillingMessage(`已在 Chrome「${body.profileLabel||'对应账号'}」中打开官方账单。请先核对账单邮箱是否与当前所选账号一致。`);}catch(error){setBillingError(error instanceof Error?error.message:'此账号的账单页面暂时无法打开。');}finally{setOpeningBilling(false);}}
  const entries=[...new Map([...(profile&&!profile.officialFields?.length?[profile]:[]),...history.filter(p=>p.email.toLowerCase()===email.toLowerCase())].map(p=>[`${p.source}:${p.observedAt}`,p])).values()].sort((a,b)=>b.observedAt.localeCompare(a.observedAt));
  const reset=profile?.resetCredits;
  const billing=profile?.officialEvidence?.billing;
  const planEvidenceAt=officialFieldStamp(profile??undefined,'planType'),resetEvidenceAt=officialFieldStamp(profile??undefined,'resetCredits'),locator=canManage?profile?.officialEvidence?.locator:undefined,resetHistory=profile?.officialEvidence?.resetHistory;
  function download(){const report={email,exportedAt:new Date().toISOString(),profile:profile??null,history:entries};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`codex-account-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <>
    {canManage&&<div className="quota-query-state"><button className="google-quota-refresh" disabled={autoQuery.saving} onClick={queryQuota}>{autoQuery.saving?'正在提交…':'查询此账号官网信息'}</button><p role="status">{autoQuery.error||accountQueryLabel(autoQuery.queries.find(q=>q.email===email||q.verified_email===email))}</p></div>}
    <div className="quota-detail-tabs" role="tablist" aria-label="账号查询内容">{([['plan','套餐与充值'],['resets','重置卡'],['history','历史额度'],['mail','Gmail 验证码'],['auth','二次认证']] as const).map(([value,title])=><button key={value} role="tab" id={`quota-tab-${value}`} aria-selected={tab===value} aria-controls="quota-detail-panel" onClick={()=>onTab(value)}>{title}</button>)}</div>
    <div id="quota-detail-panel" role="tabpanel" aria-labelledby={`quota-tab-${tab}`} className="quota-detail-panel">
    {tab==='plan'&&<>
      <div className="quota-plan-summary"><div><small>当前已读取套餐</small><strong>{plan(profile?.planType)}</strong></div><span>{planEvidenceAt?`官方页面核验 · ${stamp(planEvidenceAt)}`:isLive(profile??undefined,now,currentEmail)?'当前登录 · 实时':profile?'历史快照':'等待登录查询'}</span></div>
      <dl className="quota-detail-list"><div><dt>{billing?(billing.value.autoRenew?'自动续订日':billing.value.periodEndDate?'会员到期日':'续订日期'):'会员到期时间'}</dt><dd>{billing?(billing.value.autoRenew?billing.value.renewalDate:billing.value.periodEndDate||billing.value.renewalDate)?.replace(/^(\d{4})-(\d{2})-(\d{2})$/,'$1年$2月$3日'):stamp(profile?.subscription?.activeUntil)}</dd></div><div><dt>额外额度余额</dt><dd>{profile?.balance??'暂未提供'}</dd></div></dl>
      <p className="quota-dialog-note">{billing?`${billing.source==='official-screenshot'?'官方账单截图':'官方账单页面'}核验于 ${stamp(billing.observedAt)}。会员日期按账单原文保存，未推算具体时刻。`:'会员日期为最近核验的订阅期；续费、取消及最终扣款时间以官方账单为准。'}</p>
      <section className="quota-billing"><h3>官方充值与套餐管理</h3><p>绑卡入口按所选邮箱打开这台电脑上对应的 Chrome 个人资料。官方账单邮箱需与所选账号一致。</p>{canManage?<button className="google-quota-refresh" disabled={openingBilling} onClick={openBilling}><ArrowUpRight size={16}/>{openingBilling?'正在打开对应账号…':'在对应 Chrome 账号中绑卡 / 管理套餐'}</button>:<a className="quota-billing-primary" href="/signin-with-chatgpt?return_to=%2F%23tokens" target="_top">登录网站管理账号后打开对应账单<ArrowUpRight size={16}/></a>}{billingMessage&&<p className="google-query-success" role="status">{billingMessage}</p>}{billingError&&<p className="quota-error" role="alert">{billingError}</p>}<small>电脑和本机采集器需在线。打开对应个人资料后，请在官方页确认账单邮箱，再添加支付方式或管理套餐。<a href="https://help.openai.com/en/articles/9039756-managing-billing-for-chatgpt-and-the-api-platform" target="_blank" rel="noopener noreferrer">官方账单帮助</a></small><a href={locator?.usageUrl||'https://chatgpt.com/settings/usage?tab=overview'} target="_blank" rel="noopener noreferrer">查看官方额度页面<ArrowUpRight size={16}/></a><a href="https://chatgpt.com/pricing/" target="_blank" rel="noopener noreferrer">查看官方套餐与价格<ArrowUpRight size={15}/></a></section>
      {locator&&<details className="quota-more-details"><summary>官方页面定位与邮箱核验</summary><p className="quota-dialog-note">上次核验邮箱：{profile?.officialEvidence?.verifiedEmail}。打开页面后先核对当前登录邮箱；已保存的官方入口不会切换登录账号。</p><dl className="quota-detail-list"><div><dt>核验时间</dt><dd>{stamp(locator.verifiedAt)}</dd></div><div><dt>浏览器</dt><dd>{locator.browser?{iab:'应用内浏览器',chrome:'Chrome',edge:'Edge'}[locator.browser]:'暂未记录'}</dd></div><div><dt>官方入口</dt><dd>已保存额度与账号页面</dd></div></dl></details>}
      <details className="quota-more-details"><summary>更多账号信息</summary><dl className="quota-detail-list"><div><dt>会员开始时间</dt><dd>{stamp(profile?.subscription?.activeFrom)}</dd></div><div><dt>会员信息核验时间</dt><dd>{stamp(billing?.observedAt||profile?.subscription?.checkedAt)}</dd></div><div><dt>额度读取时间</dt><dd>{stamp(officialFieldStamp(profile??undefined,'windows')||profile?.observedAt)}</dd></div><div><dt>最近登录记录</dt><dd>{stamp(lastSeen)}</dd></div><div><dt>累计 Token</dt><dd>{total===null?'暂无记录':total.toLocaleString('zh-CN')}</dd></div></dl></details>
    </>}
    {tab==='resets'&&<>
      <div className="quota-plan-summary"><div><small>可用重置卡</small><strong>{reset?`${reset.availableCount} 张`:'尚未查询'}</strong></div><span>{resetEvidenceAt?`官方页面核验 · ${stamp(resetEvidenceAt)}`:reset?stamp(profile?.observedAt):'请登录此账号查询'}</span></div>
      {canManage?<><button className="google-quota-refresh" disabled={autoQuery.saving} onClick={queryQuota}><RefreshCw size={15} className={autoQuery.saving?'quota-spinning':''}/>{autoQuery.saving?'正在提交…':'查询此账号官网额度与重置卡'}</button><p className="quota-dialog-note" role="status">{autoQuery.error||accountQueryLabel(autoQuery.queries.find(q=>q.email===email||q.verified_email===email))}</p></>:<a className="google-quota-refresh" href="/signin-with-chatgpt?return_to=%2F%23tokens" target="_top">登录网站管理账号后查询</a>}
      {reset?.credits?.length?<div className="quota-credit-list">{reset.credits.map((c,i)=><article key={i}><div><strong>{c.title||`重置卡 ${i+1}`}</strong><span>{c.expiresAt&&c.expiresAt*1000<=now?'已到期':c.status==='available'?(resetEvidenceAt?'可用（核验时）':'可用'):c.status==='redeemed'?'已使用':c.status==='redeeming'?'使用中':'状态暂未提供'}</span></div>{c.description&&<p>{c.description}</p>}<dl><div><dt>到期时间</dt><dd>{c.expiresAt?stamp(c.expiresAt):c.expiresDateLabel||(c.noExpiry?'无固定到期时间':'暂未提供')}</dd></div><div><dt>剩余时间</dt><dd>{expiry(c.expiresAt,now,c.noExpiry,c.expiresDateLabel)}</dd></div><div><dt>发放时间</dt><dd>{stamp(c.grantedAt)}</dd></div>{c.resetType&&<div><dt>重置类型</dt><dd>{c.resetType==='codexRateLimits'?'Codex 额度重置':c.resetType==='unknown'?'未知':c.resetType}</dd></div>}</dl></article>)}</div>:<p className="quota-history-empty">{reset?(reset.availableCount===0?'该账号本次查询没有可用重置卡。':'接口暂未返回逐张明细。'):'在这台电脑登录此账号后，会自动查询重置卡数量与有效期。'}</p>}
      {resetHistory&&<><div className="quota-history-heading"><strong>官方重置历史</strong><span>{resetHistory.value.length} 条</span></div><p className="quota-dialog-note">官方页面核验于 {stamp(resetHistory.observedAt)}。获得、使用事件按实际时间展示。</p><div className="quota-history-table"><table><thead><tr><th>发生时间</th><th>事件</th></tr></thead><tbody>{[...resetHistory.value].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)).map(entry=><tr key={`${entry.kind}:${entry.occurredAt}`}><td>{stamp(entry.occurredAt)}</td><td>{entry.kind==='granted'?'获得重置卡':'使用重置卡'}</td></tr>)}</tbody></table></div></>}
      <p className="quota-dialog-note">重置卡、额外额度余额和付费即时重置分别展示。官方提供的付费即时重置会立即生效，不会存入重置卡数量。<a href="https://help.openai.com/en/articles/20001507-paid-weekly-work-and-codex-rate-limit-resets" target="_blank" rel="noopener noreferrer">查看官方说明</a></p><a className="quota-billing-primary" href={locator?.usageUrl||'https://chatgpt.com/settings/usage?tab=overview'} target="_blank" rel="noopener noreferrer">前往官方查询重置选项<ArrowUpRight size={16}/></a>
    </>}
    {tab==='history'&&<>
      <div className="quota-history-heading"><strong>历史额度记录</strong><span>{entries.length} 条</span></div><p className="quota-dialog-note">每次官网查询单独保存；部分读取只记录实际取得的字段。电脑离线、账号退出或未能读取的时段没有额度记录。</p>
      {entries.length?<div className="quota-history-table"><table><thead><tr><th>读取时间 / 来源</th><th>7 天剩余</th><th>5 小时剩余</th><th>重置卡</th></tr></thead><tbody>{entries.map(p=><tr key={`${p.source}:${p.observedAt}`}><td>{stamp(p.observedAt)}<small>{p.source==='account-api'?'账号查询':p.source==='official-page'?'官方页面核验':'本机历史记录'} · {plan(p.planType)}</small><small>周重置：{stamp(weeklyWindow(p)?.resetsAt)}</small></td><td>{percentage(p,10080)}</td><td>{percentage(p,300)}</td><td>{p.resetCredits?.availableCount??'—'}</td></tr>)}</tbody></table></div>:<p className="quota-history-empty">暂无可确认归属的额度记录，登录此账号后开始保存。</p>}
    </>}
    {tab==='mail'&&<GmailCodes key={email} email={email} canManage={canManage}/>}
    {tab==='auth'&&<AuthenticatorCodes key={email} email={email} canManage={canManage}/>}
    </div>
    <div className="quota-detail-footer"><button onClick={download} className="quota-export"><Download size={15}/>下载账号记录</button>{total!==null&&<button onClick={onStatistics}>每日 Token 统计<ArrowUpRight size={15}/></button>}</div><p className="quota-dialog-note">下载文件包含此账号的完整邮箱、会员信息与历史额度。所有时间为 UTC+8。</p>
  </>;
}
