"use client";
import {useEffect,useState,useRef} from 'react';
import {Copy,LockKeyhole,Mail,RefreshCw,ShieldCheck} from 'lucide-react';
import {parseTotp,totp,encryptTotp,decryptTotp,type TotpConfig} from '@/lib/totp';
import {parseAuthenticatorImport,readAuthenticatorQr,type AuthenticatorImport} from '@/lib/authenticator-import';
type Message={id:string;subject:string;from:string;receivedAt:string;codes:string[]};
type GmailReply={error?:string;connected?:boolean;messages?:Message[];checkedAt?:string};
const unlocked=new Map<string,TotpConfig>();
const storageKey=(email:string)=>`codex-pulse:totp-v1:${email.toLowerCase()}`;
const date=(stamp:string)=>new Date(stamp).toLocaleString('zh-CN',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});
export const googleAccountUrl=(email:string)=>`https://myaccount.google.com/?authuser=${encodeURIComponent(email)}`;
export const gmailUrl=(email:string)=>`https://mail.google.com/mail/u/?authuser=${encodeURIComponent(email)}#inbox`;
export const appPasswordsUrl=(email:string)=>`https://myaccount.google.com/apppasswords?authuser=${encodeURIComponent(email)}`;
export async function copyCode(code:string){if(!navigator.clipboard)throw new Error('当前浏览器无法复制，请长按验证码复制。');await navigator.clipboard.writeText(code);}

function PrivateLogin(){return <div className="google-private-login"><LockKeyhole size={22}/><p>请使用网站管理账号登录后，连接邮箱或查看二次认证。</p><a className="quota-submit" href="/signin-with-chatgpt?return_to=%2F%23tokens" target="_top">使用网站管理账号登录</a></div>;}

export function GmailCodes({email,canManage}:{email:string;canManage:boolean}){
  const [connected,setConnected]=useState(false),[checked,setChecked]=useState(false),[messages,setMessages]=useState<Message[]>([]),[checkedAt,setCheckedAt]=useState(''),[password,setPassword]=useState(''),[connecting,setConnecting]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(''),[now,setNow]=useState(Date.now());
  const sequence=useRef(0),connectionVersion=useRef(0);
  const endpoint=(action:string)=>`/api/local-apps/identity/${action}?email=${encodeURIComponent(email)}`;
  useEffect(()=>{const version=++connectionVersion.current;setChecked(false);setConnected(false);setMessages([]);setPassword('');setError('');setConnecting(false);const abort=new AbortController();if(canManage)fetch(endpoint('status'),{cache:'no-store',signal:abort.signal}).then(async r=>{const b=await r.json() as GmailReply;if(version!==connectionVersion.current||abort.signal.aborted)return;if(!r.ok)throw new Error(b.error||'连接状态暂时无法读取');setConnected(b.connected===true);setChecked(true);}).catch(e=>{if(!abort.signal.aborted&&version===connectionVersion.current){setError(e.message);setChecked(true);}});return()=>{abort.abort();++sequence.current;++connectionVersion.current;};},[email,canManage]);
  useEffect(()=>{if(!canManage||!connected)return;const abort=new AbortController();let pending=false;const version=connectionVersion.current;async function load(){if(pending||document.hidden)return;pending=true;const current=++sequence.current;setBusy(true);try{const r=await fetch(endpoint('gmail-codes'),{cache:'no-store',signal:abort.signal}),b=await r.json() as GmailReply;if(!r.ok)throw new Error(b.error||'读取 Gmail 失败');if(current!==sequence.current||version!==connectionVersion.current)return;setConnected(b.connected===true);setMessages(b.messages||[]);setCheckedAt(b.checkedAt||'');setError('');}catch(e){if(!abort.signal.aborted&&current===sequence.current&&version===connectionVersion.current){setError(e instanceof Error?e.message:'读取失败');}}finally{pending=false;if(!abort.signal.aborted&&current===sequence.current)setBusy(false);}}load();const timer=setInterval(load,15000),tick=setInterval(()=>setNow(Date.now()),1000);document.addEventListener('visibilitychange',load);return()=>{abort.abort();clearInterval(timer);clearInterval(tick);document.removeEventListener('visibilitychange',load);++sequence.current;};},[email,connected,canManage]);
  async function connect(event:React.FormEvent){event.preventDefault();const version=++connectionVersion.current;setConnecting(true);setError('');try{const r=await fetch(endpoint('gmail-connection'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'connect',password})}),b=await r.json() as GmailReply;if(version!==connectionVersion.current)return;if(!r.ok)throw new Error(b.error||'连接失败');setConnected(true);setPassword('');setChecked(true);}catch(e){if(version===connectionVersion.current)setError(e instanceof Error?e.message:'连接失败');}finally{if(version===connectionVersion.current)setConnecting(false);}}
  async function disconnect(){const version=connectionVersion.current;setConnecting(true);try{const r=await fetch(endpoint('gmail-connection'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'disconnect'})}),b=await r.json() as GmailReply;if(version!==connectionVersion.current)return;if(!r.ok)throw new Error(b.error||'断开失败');++connectionVersion.current;++sequence.current;setConnected(false);setMessages([]);setError('');}catch(e){if(version===connectionVersion.current)setError(e instanceof Error?e.message:'断开失败');}finally{if(version===connectionVersion.current||version+1===connectionVersion.current)setConnecting(false);}}
  async function copy(value:string,id:string){try{await copyCode(value);setCopied(id);setTimeout(()=>setCopied(''),2000);}catch(e){setError(e instanceof Error?e.message:'复制失败');}}
  if(!canManage)return <PrivateLogin/>;
  return <div className="google-tool-panel"><div className="google-tool-heading"><Mail size={20}/><div><strong>Gmail 验证码</strong><small>{connected?'每 15 秒检查一次最近 15 分钟的验证码邮件':'此邮箱尚未连接自动收码'}</small></div><a href={gmailUrl(email)} target="_blank" rel="noopener noreferrer">打开 Gmail</a></div>
    <p className="quota-dialog-note">{email} · 请在 Google 页面核对右上角登录邮箱。</p>
    {error&&<p className="quota-error" role="status">{error}</p>}
    {!checked?<p className="google-empty">正在读取连接状态…</p>:!connected?<form className="google-connection-form" onSubmit={connect}><p>连接后可在这里直接查收、复制验证码。使用 Google 为此邮箱生成的应用专用密码，不要输入 Google 登录密码。</p><a href={appPasswordsUrl(email)} target="_blank" rel="noopener noreferrer">查看或新建应用专用密码</a><label>Gmail 应用专用密码<input type="password" required autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} maxLength={24} placeholder="Google 生成的 16 位密码"/></label><p className="quota-dialog-note">连接密码会加密保存在原电脑。邮箱只读取验证码候选邮件，电脑需保持开机联网。</p><button className="quota-submit" disabled={connecting}>{connecting?'正在验证连接…':'连接 Gmail 自动收码'}</button></form>:<>
      <div className="google-read-status"><span>{busy?<><RefreshCw size={14} className="quota-spinning"/>正在检查新邮件</>:checkedAt?`上次读取：${date(checkedAt)}`:'等待首次读取'}</span><button disabled={connecting} onClick={disconnect}>断开本机连接</button></div>
      {messages.filter(m=>now-Date.parse(m.receivedAt)<=15*60000).length?<div className="google-mail-list">{messages.filter(m=>now-Date.parse(m.receivedAt)<=15*60000).map(message=><article key={message.id}><strong>{message.subject}</strong><small>{message.from}<br/>{date(message.receivedAt)}</small><div>{message.codes.map(code=><button key={code} className="google-copy-code" onClick={()=>copy(code,message.id+code)}><span>{code}</span><Copy size={15}/><small>{copied===message.id+code?'已复制':'复制'}</small></button>)}</div></article>)}</div>:<p className="google-empty">{busy?'正在读取最近邮件…':'最近 15 分钟没有识别到验证码邮件。新邮件到达后会自动出现。'}</p>}
      <p className="quota-dialog-note">显示的是候选验证码，请核对邮件来源和时间。未更改邮件已读状态，也不会发送邮件。</p>
    </>}
  </div>;
}

export function AuthenticatorCodes({email,canManage}:{email:string;canManage:boolean}){
  const [config,setConfig]=useState<TotpConfig|null>(null),[stored,setStored]=useState(false),[input,setInput]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState(''),[until,setUntil]=useState(0),[now,setNow]=useState(Date.now()),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[removing,setRemoving]=useState(false),[imported,setImported]=useState<AuthenticatorImport|null>(null),[choice,setChoice]=useState(0),[mapped,setMapped]=useState(false);
  const epoch=useRef(0);
  useEffect(()=>{++epoch.current;if(!canManage)unlocked.clear();setConfig(canManage?unlocked.get(email)||null:null);setInput('');setPassword('');setConfirm('');setCode('');setError('');setBusy(false);setImported(null);setMapped(false);setRemoving(false);try{setStored(!!localStorage.getItem(storageKey(email)));}catch{setStored(false);}return()=>{++epoch.current;};},[email,canManage]);
  useEffect(()=>{if(!config||!canManage)return;let active=true,sequence=0;async function refresh(){const current=++sequence;setNow(Date.now());if(document.hidden){setCode('');return;}try{const result=await totp(config!);if(active&&current===sequence&&!document.hidden){setCode(result.validUntil>Date.now()?result.code:'');setUntil(result.validUntil);}}catch{if(active&&current===sequence)setError('无法生成此二次认证码，请重新导入。');}}refresh();const timer=setInterval(refresh,1000);document.addEventListener('visibilitychange',refresh);return()=>{active=false;++sequence;clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[config,canManage]);
  async function save(event:React.FormEvent){event.preventDefault();const current=++epoch.current;setError('');setBusy(true);try{if(password!==confirm)throw new Error('两次解锁密码不一致。');if(imported&&!mapped)throw new Error('请确认所选认证条目对应此账号。');const next=imported?imported.entries[choice]:parseTotp(input,email),cipher=await encryptTotp(next,password,email);if(current!==epoch.current)return;localStorage.setItem(storageKey(email),JSON.stringify(cipher));unlocked.set(email,next);setConfig(next);setStored(true);setInput('');setPassword('');setConfirm('');setImported(null);setMapped(false);}catch(e){if(current===epoch.current)setError(e instanceof Error?e.message:'保存失败');}finally{if(current===epoch.current)setBusy(false);}}
  async function unlock(event:React.FormEvent){event.preventDefault();const current=++epoch.current;setError('');setBusy(true);try{const next=await decryptTotp(JSON.parse(localStorage.getItem(storageKey(email))||'null'),password,email);if(current!==epoch.current)return;unlocked.set(email,next);setConfig(next);setPassword('');}catch(e){if(current===epoch.current)setError(e instanceof Error?e.message:'解锁失败');}finally{if(current===epoch.current)setBusy(false);}}
  function lock(){++epoch.current;unlocked.delete(email);setConfig(null);setCode('');setCopied(false);setBusy(false);}
  function remove(){try{localStorage.removeItem(storageKey(email));lock();setStored(false);setRemoving(false);}catch{setError('当前浏览器无法移除保存的数据。');}}
  async function copy(){if(!config)return;const current=epoch.current;try{let result=await totp(config);if(result.validUntil<=Date.now())result=await totp(config);if(current!==epoch.current)return;if(result.validUntil<=Date.now())throw new Error('验证码刚好到期，请重新复制。');await copyCode(result.code);if(current!==epoch.current)return;setCode(result.code);setUntil(result.validUntil);setCopied(true);setTimeout(()=>{if(current===epoch.current)setCopied(false);},1500);}catch(e){if(current===epoch.current)setError(e instanceof Error?e.message:'复制失败');}}
  async function importQr(file:File){const current=++epoch.current;setBusy(true);setError('');try{const result=await readAuthenticatorQr(file,email);if(current!==epoch.current)return;setImported(result);setChoice(0);setMapped(false);setInput('');}catch(e){if(current===epoch.current)setError(e instanceof Error?e.message:'二维码读取失败');}finally{if(current===epoch.current)setBusy(false);}}
  function importLink(){try{setImported(parseAuthenticatorImport(input,email));setChoice(0);setMapped(false);setInput('');setError('');}catch(e){setError(e instanceof Error?e.message:'无法识别导出链接');}}
  if(!canManage)return <PrivateLogin/>;
  return <div className="google-tool-panel"><div className="google-tool-heading"><ShieldCheck size={20}/><div><strong>Google Authenticator</strong><small>兼容六位 TOTP 时间验证码</small></div></div><p className="quota-dialog-note">导入此账号的原始二次认证密钥后，可在这里实时查看、复制验证码。Google 登录不会自动取得 Authenticator 中的密钥。</p>
    {error&&<p className="quota-error" role="alert">{error}</p>}
    {config?<><div className="google-auth-display"><small>{config.issuer} · {config.label}</small><strong aria-label="当前六位二次认证码">{now<until&&code?code:'······'}</strong><div><span>{Math.max(0,Math.ceil((until-now)/1000))} 秒后更新</span><button className="google-copy-code" disabled={!code||now>=until} onClick={copy}><Copy size={16}/>{copied?'已复制':'复制当前验证码'}</button></div><progress max={config.period} value={Math.max(0,(until-now)/1000)} aria-label="验证码剩余时间"/></div><button className="google-subtle" onClick={lock}>锁定本浏览器认证码</button></>:stored?<form className="google-connection-form" onSubmit={unlock}><label>本浏览器解锁密码<input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="quota-submit" disabled={busy}>{busy?'正在解锁…':'解锁并开始自动刷新'}</button></form>:<form className="google-connection-form" onSubmit={save}>
      {!imported?<><label>二次认证密钥或 otpauth 链接<input type="password" autoComplete="off" value={input} onChange={e=>setInput(e.target.value)} required maxLength={35000} placeholder="Base32 密钥 / otpauth://totp/..."/></label>{input.startsWith('otpauth-migration:')&&<button type="button" onClick={importLink}>读取 Authenticator 导出链接</button>}<label className="google-qr-file">或导入 Authenticator 导出二维码<input type="file" accept="image/*" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)importQr(file);}}/></label><small>Authenticator → 转移验证码 → 导出验证码，选择对应条目。图片只在浏览器读取。</small></>:<div className="google-import-choice"><label>选择与 {email} 对应的认证条目<select value={choice} onChange={e=>{setChoice(Number(e.target.value));setMapped(false);}}>{imported.entries.map((c,i)=><option key={i} value={i}>{c.issuer} · {c.label}</option>)}</select></label><small>已读取第 {imported.page} / {imported.totalPages} 页。{imported.skipped?`跳过 ${imported.skipped} 个非六位 TOTP 条目。`:''}每次导入一个条目；目标不在这一页时请选择其他二维码。</small><label className="google-mapping-confirm"><input type="checkbox" checked={mapped} onChange={e=>setMapped(e.target.checked)} required/>确认此认证条目对应本网站的 {email}</label><button type="button" onClick={()=>{setImported(null);setMapped(false);}}>重新选择密钥或二维码</button></div>}
      <label>设置本浏览器解锁密码<input type="password" minLength={8} required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="至少 8 个字符"/></label><label>再次输入解锁密码<input type="password" minLength={8} required autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="quota-dialog-note">密钥加密保存在此浏览器，计算和复制均在本地完成。请自行保管解锁密码。</p><button className="quota-submit" disabled={busy}>{busy?'正在处理…':'导入并开始显示六位码'}</button></form>}
    {stored&&<div className="google-remove-auth">{removing?<><p>移除此浏览器保存的认证密钥？原 Google Authenticator 中的账号会保留。</p><button onClick={remove}>确认移除本机副本</button><button onClick={()=>setRemoving(false)}>取消</button></>:<button onClick={()=>setRemoving(true)}>移除此浏览器的密钥副本</button>}</div>}
  </div>;
}
