"use client";
import {useEffect,useState,useCallback,useRef} from 'react';
import {Eye,EyeOff,RefreshCw,Plus,ChartNoAxesCombined,Search,MoreHorizontal,ArrowUpRight,Mail,ShieldCheck} from 'lucide-react';
import AccountDetails,{type DetailTab} from './account-details';
import {googleAccountUrl} from './account-google-tools';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {weeklyWindow,remaining,isLive,resetSort,type KnownAccount,type QuotaProfile,type QuotaRegistration} from '@/lib/quota';
import {officialFieldStamp} from '@/lib/quota-evidence';
import {useAccountQueries,accountQueryLabel} from './use-account-queries';

const stamp=(value:string|number|null|undefined)=>value?new Date(typeof value==='number'?value*1000:value).toLocaleString('zh-CN',{timeZone:'Asia/Taipei',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}):'暂未提供';
function duration(seconds:number){if(seconds<=0)return '等待重新查询';const minutes=Math.ceil(seconds/60),days=Math.floor(minutes/1440),hours=Math.floor(minutes%1440/60);return `${days?`${days}天`:''}${hours?`${hours}小时`:''}${!days&&!hours?`${minutes}分钟`:''}后重置`;}
function age(value:string,now:number){const seconds=Math.max(0,Math.floor((now-Date.parse(value))/1000));return seconds<60?`${seconds}秒前`:seconds<3600?`${Math.floor(seconds/60)}分钟前`:stamp(value);}
const plan=(value?:string|null)=>value?({pro:'Pro',plus:'Plus',free:'Free',team:'Team',business:'Business',enterprise:'Enterprise'}[value]||value):'套餐待查询';
const mask=(email:string)=>{const [local,domain]=email.split('@');return `${local.length>2?local.slice(0,2):'•'}••••@${domain}`;};
type Props={currentAccountEmail:string|null;accounts:KnownAccount[];profiles:QuotaProfile[];history:QuotaProfile[];refreshToken:number;onRefresh:()=>void;onStatistics:(id?:string)=>void;totals:Record<string,number>};

export default function AccountOverview({currentAccountEmail,accounts,profiles,history,refreshToken,onRefresh,onStatistics,totals}:Props){
  const [registrations,setRegistrations]=useState<QuotaRegistration[]>([]),[canManage,setCanManage]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const [query,setQuery]=useState(''),[sort,setSort]=useState('reset'),[privateMode,setPrivateMode]=useState(true),[revealed,setRevealed]=useState<Record<string,boolean>>({}),[now,setNow]=useState(Date.now());
  const [adding,setAdding]=useState(false),[email,setEmail]=useState(''),[name,setName]=useState(''),[saving,setSaving]=useState(false),[formError,setFormError]=useState(''),[detail,setDetail]=useState<string|null>(null),[removing,setRemoving]=useState<string|null>(null),[showRemoved,setShowRemoved]=useState(false);
  const [detailTab,setDetailTab]=useState<DetailTab>('plan');
  const autoQuery=useAccountQueries(canManage,onRefresh);
  function openDetail(email:string,tab:DetailTab='plan'){setDetail(email.toLowerCase());setDetailTab(tab);}
  const loadSequence=useRef(0);
  const load=useCallback(async(signal?:AbortSignal)=>{const sequence=++loadSequence.current;setLoading(true);try{const response=await fetch('/api/accounts',{cache:'no-store',signal});const body=await response.json() as {accounts:QuotaRegistration[];canManage:boolean;error?:string};if(!response.ok)throw new Error(body.error||'账号列表暂时无法读取');if(sequence!==loadSequence.current)return;setRegistrations(body.accounts);setCanManage(body.canManage===true);setError('');}catch(e){if(sequence===loadSequence.current&&!(e instanceof DOMException&&e.name==='AbortError'))setError(e instanceof Error?e.message:'连接中断，已保留账号记录');}finally{if(sequence===loadSequence.current&&!signal?.aborted)setLoading(false);}},[]);
  useEffect(()=>{const c=new AbortController();load(c.signal);const timer=setInterval(()=>load(c.signal),60000);return()=>{c.abort();clearInterval(timer);};},[load,refreshToken]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);try{setPrivateMode(localStorage.getItem('codex-pulse:quota-privacy')!=='show');}catch{}return()=>clearInterval(timer);},[]);
  const all=new Map<string,{email:string;id?:string;name:string;hidden:boolean;lastSeen?:string;profile?:QuotaProfile}>();
  for(const a of accounts)all.set(a.email.toLowerCase(),{email:a.email,id:a.id,name:a.email.split('@')[0],hidden:false,lastSeen:a.lastSeen});
  for(const p of profiles){const key=p.email.toLowerCase();all.set(key,{...(all.get(key)||{email:p.email,name:p.email.split('@')[0],hidden:false}),profile:p});}
  for(const r of registrations){const key=r.email.toLowerCase(),a=all.get(key);all.set(key,{...(a||{email:r.email,name:r.email.split('@')[0]}),name:r.name||a?.name||r.email.split('@')[0],hidden:!!r.hidden});}
  const shown=[...all.values()].filter(a=>!a.hidden),removed=[...all.values()].filter(a=>a.hidden),visible=shown.filter(a=>`${a.email} ${a.name}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==='name'?a.email.localeCompare(b.email):sort==='remaining'?(remaining(weeklyWindow(a.profile))??Infinity)-(remaining(weeklyWindow(b.profile))??Infinity):resetSort(weeklyWindow(a.profile),weeklyWindow(b.profile))||a.email.localeCompare(b.email));
  const selected=detail?all.get(detail):undefined;
  async function mutate(action:string,target:string,label=''){setSaving(true);setFormError('');try{const response=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email:target,name:label})});const body=await response.json() as {ok?:boolean;error?:string};if(!response.ok)throw new Error(body.error||'保存失败');++loadSequence.current;setRegistrations(previous=>[...previous.filter(r=>r.email!==target.toLowerCase()),{email:target.toLowerCase(),name:action==='add'?label:previous.find(r=>r.email===target.toLowerCase())?.name||'',hidden:action==='hide'?1:0}]);await load();setAdding(false);setRemoving(null);setEmail('');setName('');}catch(e){setFormError(e instanceof Error?e.message:'保存失败，请重试');}finally{setSaving(false);}}
  function refresh(){if(canManage)void autoQuery.request(null);else onRefresh();}
  function togglePrivacy(){setPrivateMode(value=>{try{localStorage.setItem('codex-pulse:quota-privacy',value?'show':'hide');}catch{}return !value;});setRevealed({});}
  const dateOnly=(value?:string|null)=>value?new Date(value).toLocaleDateString('zh-CN',{timeZone:'Asia/Taipei'}):'暂未提供';
  return <section className="quota-overview" aria-label="Codex 账号额度总览">
    <header className="quota-header"><div className="quota-heading"><h2>Codex 额度总览</h2><span>{shown.length} 个账号 · 按实际核验时间保存</span></div><div className="quota-actions"><button aria-label={privateMode?'显示全部邮箱':'隐藏全部邮箱'} title={privateMode?'显示全部邮箱':'隐藏全部邮箱'} onClick={togglePrivacy}>{privateMode?<EyeOff size={18}/>:<Eye size={18}/>}</button><button aria-label="查询 Edge 当前账号" title={canManage?'提交 Edge 当前账号官网查询':'刷新已保存信息'} disabled={loading||autoQuery.saving} onClick={refresh}><RefreshCw size={18} className={loading||autoQuery.saving?'quota-spinning':''}/></button><button aria-label="管理已移除账号" title="管理已移除账号" aria-expanded={showRemoved} onClick={()=>setShowRemoved(v=>!v)}><MoreHorizontal size={20}/></button><button className="quota-add" onClick={()=>{setAdding(true);setFormError('');}}><Plus size={17}/>添加账号</button></div></header>
    {canManage&&<div className="quota-auto-query"><label><input type="checkbox" checked={!!autoQuery.control?.enabled} disabled={autoQuery.saving||!autoQuery.control} onChange={e=>void autoQuery.configure(e.target.checked)}/>自动记录 Edge 已登录账号</label><span>{autoQuery.workerOnline?'后台最近检查过':'等待后台连接'} · {accountQueryLabel(autoQuery.queries[0])}</span><small>连接有效时每 5 分钟核对；查询成功后自动保存额度、重置卡和会员日期。登录失效时保留旧记录。</small>{autoQuery.error&&<p role="status">{autoQuery.error}</p>}</div>}
    <div className="quota-toolbar"><span>账号总览（{shown.length}）</span><label className="quota-search"><Search size={15}/><input aria-label="查询账号" placeholder="查询邮箱或账号名" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="quota-text-button" onClick={()=>onStatistics()}>每日 Token 统计<ArrowUpRight size={14}/></button><label className="quota-sort"><span>排序</span><select aria-label="账号排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="reset">重置时间：从早到晚</option><option value="remaining">剩余额度：从少到多</option><option value="name">账号名称</option></select></label></div>
    {error&&<p className="quota-message" role="status">{error}。已同步的账号仍可查看。</p>}
    {showRemoved&&<div className="quota-removed"><strong>已移除账号（{removed.length}）</strong>{removed.length?removed.map(a=><div key={a.email}><span>{privateMode?mask(a.email):a.email}</span><button disabled={!canManage||saving} onClick={()=>mutate('restore',a.email)}>恢复显示</button></div>):<p>暂无已移除的账号。</p>}</div>}
    <div className="quota-grid">{visible.map(a=>{const p=a.profile,w=weeklyWindow(p),left=remaining(w),live=isLive(p,now,currentAccountEmail),expired=!!w?.resetsAt&&w.resetsAt*1000<=now,reveal=revealed[a.email]??!privateMode,until=p?.subscription?.activeUntil,displayName=!reveal&&a.name===a.email.split('@')[0]?mask(a.email).split('@')[0]:a.name,nearExpiry=!!until&&Date.parse(until)-now<7*86400000;return <article className="quota-card" key={a.email}>
      <div className="quota-card-top"><div className="quota-identity"><button className="quota-account-name" onClick={()=>openDetail(a.email)}>{displayName}</button><span className="quota-email">{reveal?a.email:mask(a.email)}</span></div><div className="quota-card-tools"><button aria-label={`查询 ${displayName} 的官网信息`} title="查询此邮箱在 Edge 的官网信息" disabled={loading||autoQuery.saving} onClick={()=>canManage?void autoQuery.request(a.email):onRefresh()}><RefreshCw size={15}/></button><button aria-label={`${reveal?'隐藏':'显示'} ${displayName} 的邮箱`} onClick={()=>setRevealed(v=>({...v,[a.email]:!reveal}))}>{reveal?<Eye size={16}/>:<EyeOff size={16}/>}</button><button className="quota-plan" title="查询套餐与充值" onClick={()=>openDetail(a.email)}>{plan(p?.planType)}</button></div></div>
      {canManage&&autoQuery.queries.some(q=>q.email===a.email||q.verified_email===a.email)&&<p className="quota-query-state" role="status">{accountQueryLabel(autoQuery.queries.find(q=>q.email===a.email||q.verified_email===a.email))}</p>}
      <div className="quota-status"><span className={live?'quota-live':''}>{officialFieldStamp(p,'windows')?'官方页面核验额度':live?'当前登录 · 实时额度':p?'历史额度 · 非实时':'待查询额度'}</span>{p&&<span>读取于 {stamp(officialFieldStamp(p,'windows')||p.observedAt)}</span>}</div>
      <div className="quota-window-row"><span>7天额度</span><span>{left===null?'暂未提供':`${left.toFixed(left%1?1:0)}% 剩余`}{w?.resetsAt?` · ${duration(w.resetsAt-now/1000)}（${stamp(w.resetsAt)}）`:''}</span></div>
      <div className={`quota-progress ${left===null?'quota-unknown':''}`} role="progressbar" aria-label={`${displayName} 七天剩余额度`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={left??undefined} aria-valuetext={left===null?'暂未提供':`${left}% 剩余${live&&!expired?'':'，上次读取值'}`}><span style={{width:`${left??0}%`,background:left!==null&&left<=10?'#ee5265':left!==null&&left<=25?'#f6a21a':'#19bc89'}}/></div>
      <button className="quota-reset" title="查看重置卡明细" onClick={()=>openDetail(a.email,'resets')}>重置卡：{p?.resetCredits?`${p.resetCredits.availableCount} 张可用`:'尚未查询'}{officialFieldStamp(p,'resetCredits')?' · 官方核验':''} <ArrowUpRight size={13}/></button>
      <div className="quota-card-meta"><span>最近更新：{p?age(p.officialEvidence&&p.officialEvidence.observedAt>p.observedAt?p.officialEvidence.observedAt:p.observedAt,now):'等待登录查询'}</span>{p?.officialEvidence?.billing?<span>{p.officialEvidence.billing.value.autoRenew?'自动续订':p.officialEvidence.billing.value.periodEndDate?'会员到期':'续订日期'}：{(p.officialEvidence.billing.value.autoRenew?p.officialEvidence.billing.value.renewalDate:p.officialEvidence.billing.value.periodEndDate||p.officialEvidence.billing.value.renewalDate)?.replaceAll('-','/')}</span>:<span className={nearExpiry?'quota-expiring':''}>会员到期：{dateOnly(until)}</span>}</div>
      <div className="quota-card-bottom"><div className="quota-card-links"><button className="quota-details-link" onClick={()=>openDetail(a.email)}>套餐查询</button><button className="quota-details-link" onClick={()=>openDetail(a.email,'history')}>历史额度</button></div><div><button className="quota-remove" onClick={()=>{setRemoving(a.email);setFormError('');}}>移除</button><button className="quota-chart" aria-label={`查看 ${displayName} 的每日 Token 统计`} title="每日 Token 统计" disabled={!a.id} onClick={()=>onStatistics(a.id)}><ChartNoAxesCombined size={17}/></button></div></div>
      <div className="quota-google-links"><a href={googleAccountUrl(a.email)} target="_blank" rel="noopener noreferrer">Google 账号<ArrowUpRight size={13}/></a><button onClick={()=>openDetail(a.email,'mail')}><Mail size={14}/>Gmail 验证码</button><button onClick={()=>openDetail(a.email,'auth')}><ShieldCheck size={14}/>二次认证</button></div>
    </article>;})}</div>
    {!visible.length&&<p className="quota-empty">{query?'没有找到匹配的账号。':'暂无账号，添加邮箱或在这台电脑登录 Codex 后会自动出现。'}</p>}
    <p className="quota-footnote">后台连接有效时定时核对 Edge 官网完整邮箱，并按邮箱保存查询结果。登录或切换账号会在下一次核对时发现；电脑离线、连接中断或退出登录时显示最后核验记录。所有时间为 UTC+8。</p>
    <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="quota-dialog"><DialogTitle>添加账号</DialogTitle><DialogDescription>添加邮箱后会出现在额度总览。在这台电脑登录该 Codex 账号后，将自动读取它的额度。</DialogDescription>{canManage?<form onSubmit={e=>{e.preventDefault();mutate('add',email,name);}}><label>账号邮箱<input autoFocus required type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label><label>账号名称（可选）<input maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="方便识别的名称"/></label>{formError&&<p className="quota-error" role="alert">{formError}</p>}<button className="quota-submit" disabled={saving}>{saving?'正在保存…':'添加账号'}</button></form>:<a className="quota-submit" href="/signin-with-chatgpt?return_to=%2F%23tokens" target="_top">使用网站管理账号登录</a>}</DialogContent></Dialog>
    <Dialog open={!!removing} onOpenChange={value=>{if(!value)setRemoving(null);}}><DialogContent className="quota-dialog"><DialogTitle>移除账号卡片</DialogTitle><DialogDescription>将 {privateMode&&removing?mask(removing):removing} 从额度总览移除。Token 历史记录会保留，可通过右上角菜单恢复卡片。</DialogDescription>{formError&&<p className="quota-error" role="alert">{formError}</p>}{canManage?<button className="quota-submit quota-danger" disabled={saving} onClick={()=>removing&&mutate('hide',removing)}>{saving?'正在保存…':'确认移除'}</button>:<a className="quota-submit" href="/signin-with-chatgpt?return_to=%2F%23tokens" target="_top">使用网站管理账号登录</a>}</DialogContent></Dialog>
    <Dialog open={!!selected} onOpenChange={value=>{if(!value)setDetail(null);}}><DialogContent className="quota-dialog quota-detail-dialog"><DialogTitle>账号信息</DialogTitle><DialogDescription>{selected&&((revealed[selected.email]??!privateMode)?selected.email:mask(selected.email))}{selected&&<button className="quota-reveal-detail" onClick={()=>setRevealed(v=>({...v,[selected.email]:!(v[selected.email]??!privateMode)}))}>{(revealed[selected.email]??!privateMode)?'隐藏邮箱':'显示邮箱'}</button>}</DialogDescription>{selected&&<AccountDetails key={selected.email} email={selected.email} profile={selected.profile} history={history} lastSeen={selected.lastSeen} total={selected.id?(totals[selected.id]||0):null} currentEmail={currentAccountEmail} now={now} tab={detailTab} onTab={setDetailTab} canManage={canManage} onRefresh={onRefresh} onStatistics={()=>{onStatistics(selected.id);setDetail(null);}}/>}</DialogContent></Dialog>
  </section>;
}
