"use client";
import {useEffect,useState} from "react";
import {Wallet,Plus,LockKeyhole,Check,X,Trash2} from "lucide-react";
type Account={id:string;label:string;balance:string|null;unlimited:number;observedAt:string;confirmed:number;pending:number};
type Change={id:string;accountLabel:string;direction:string;amount:string;usdMicros:number;beforeBalance:string;afterBalance:string;observedAt:string;classification:string};
type Entry={id:string;entryDate:string;currency:string;amount:string;usdMicros:number;rate:string;rateDate:string;note:string};
type Data={accounts:Account[];changes:Change[];entries:Entry[];totals:{manual:number;confirmed:number;pending:number};status:{lastPoll:string|null;lastSync:string;state:string}|null;canManage:boolean};
const money=(micros:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(micros/1e6),date=(s:string)=>new Date(s).toLocaleString("zh-CN",{timeZone:"Asia/Taipei",hour12:false}),today=()=>new Date(Date.now()+8*3600000).toISOString().slice(0,10);
const classification:Record<string,string>={pending:"待核实",spent:"已确认消耗",expired:"到期失效",adjustment:"其他调整",observed:"余额增加"};
export default function Ledger(){
 const [account,setAccount]=useState("");
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false),[removeId,setRemoveId]=useState<string|null>(null);
 const [form,setForm]=useState<{id:string;date:string;currency:string;amount:string;note:string}|null>(null),[rate,setRate]=useState<{rate:number;date:string;source:string}|null>(null),[rateError,setRateError]=useState("");
 useEffect(()=>{let active=true,pending=false;const controller=new AbortController();async function load(){if(pending)return;pending=true;try{const response=await fetch(`/api/ledger?account=${encodeURIComponent(account)}`,{cache:"no-store",signal:AbortSignal.any([controller.signal,AbortSignal.timeout(12000)])}),value=await response.json() as Data&{error:string};if(!response.ok)throw new Error(value.error);if(active){setData(value);setError("");}}catch(e){if(active)setError(e instanceof Error?e.message:"连接失败，正在重试");}finally{pending=false;}}load();const timer=setInterval(load,10000);return()=>{active=false;controller.abort();clearInterval(timer);};},[refresh,account]);
 useEffect(()=>{setRate(null);setRateError("");if(!form)return;let active=true;const controller=new AbortController();const timer=setTimeout(async()=>{try{const response=await fetch(`/api/ledger/rate?currency=${encodeURIComponent(form.currency)}&date=${form.date}`,{signal:controller.signal}),value=await response.json() as {rate:number;date:string;source:string;error:string};if(!response.ok)throw new Error(value.error);if(active)setRate(value);}catch(e){if(active)setRateError(e instanceof Error?e.message:"汇率暂不可用");}},400);return()=>{active=false;clearTimeout(timer);controller.abort();};},[form?.currency,form?.date]);
 async function save(e:React.FormEvent){e.preventDefault();if(!form)return;setBusy(true);setNotice("");try{const response=await fetch("/api/ledger",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),value=await response.json() as {error:string};if(!response.ok)throw new Error(value.error);setForm(null);setNotice("已按保存时的汇率记账，美元金额与原币金额都已保存");setRefresh(n=>n+1);}catch(e){setNotice(e instanceof Error?e.message:"保存失败，内容已保留");}finally{setBusy(false);}}
 async function classify(id:string,value:string){setBusy(true);try{const response=await fetch("/api/ledger",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"classify",id,classification:value})});if(!response.ok)throw new Error("分类保存失败，请重试");setRefresh(n=>n+1);setNotice("已更新余额变化的分类");}catch(e){setNotice(e instanceof Error?e.message:"操作失败");}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);try{const response=await fetch(`/api/ledger?id=${id}`,{method:"DELETE"});if(!response.ok)throw new Error("删除失败，请重试");setRemoveId(null);setRefresh(n=>n+1);setNotice("已删除这笔手动支出");}catch(e){setNotice(e instanceof Error?e.message:"操作失败");}finally{setBusy(false);}}
 const total=(data?.totals.manual||0)+(data?.totals.confirmed||0),balance=data?.accounts.reduce((sum,a)=>sum+(!a.unlimited&&a.balance!==null?Number(a.balance)*40000:0),0)||0;
 const finiteAccounts=data?.accounts.filter(a=>!a.unlimited&&a.balance!==null)||[],creditBalance=finiteAccounts.reduce((sum,a)=>sum+Number(a.balance),0),unknownAccounts=data?.accounts.filter(a=>!a.unlimited&&a.balance===null).length||0,unlimitedAccounts=data?.accounts.filter(a=>a.unlimited).length||0;
 const stale=!!data?.status?.lastPoll&&Date.now()-Date.parse(data.status.lastPoll)>180000;
 return <section className="ledger-view"><div className="intro"><div><p className="eyebrow">额度与支出 · 美元</p><h1>额度账本</h1></div>{data?.canManage?<button className="library-button primary" onClick={()=>{setForm({id:crypto.randomUUID(),date:today(),currency:"PHP",amount:"",note:""});setNotice("");}}><Plus size={16}/>记一笔支出</button>:<a className="library-button" href="/signin-with-chatgpt?return_to=%2F%23ledger" target="_top"><LockKeyhole size={15}/>登录记账</a>}</div>
 <div className="ledger-summary"><div className="ledger-total"><span>所有账号 · 累计已确认支出</span><strong>{data?money(total):"—"}</strong><small>全部已确认额度消耗 + 手动支出</small></div><div><span>所有账号 · 待核实减少</span><strong>{data?money(data.totals.pending):"—"}</strong><small>确认是消费后，计入已确认支出</small></div><div><span>所有账号 · 额度余额总计</span><strong>{data?.accounts.some(a=>a.balance!==null&&!a.unlimited)?money(balance):"—"}</strong><small>{finiteAccounts.length?`${creditBalance.toLocaleString(undefined,{maximumFractionDigits:4})} 额度 · ${finiteAccounts.length} 个账号`:"尚无可相加的余额"}{unknownAccounts?` · ${unknownAccounts} 个余额未知`:""}{unlimitedAccounts?` · ${unlimitedAccounts} 个不限额度`:""}<br/>250 额度 = $10 · 合计各账号最后记录的余额</small></div></div>
 <div className="ledger-explanation"><Wallet size={18}/><p>每分钟自动读取当前 Codex 账号的余额，切换账号后分别保存，历史记录持续保留。首次读取作为起点；之后的减少会保存为“待核实”，可标记为消耗、过期或调整。余额属于账号范围，可能包含其他设备的变化；断线期间只记录净变化。</p></div>
 <div className="library-status"><span>{!data?.status?"等待首次余额读取":stale?"采集器离线，显示最后记录":data.status.state==="ready"?"余额监测已连接":data.status.state==="identity-unavailable"?"当前 Codex 版本无法识别账号，暂不计算差额":"余额暂不可读，正在自动重试"}</span><span>{data?.status?.lastPoll?`最近检查 ${date(data.status.lastPoll)}`:"历史使用金额不会从 Token 推算"}</span></div>
 {error&&<p className="library-message" role="alert">{error}</p>}{notice&&<p className="library-message" role="status">{notice}</p>}
 {form&&<form className="library-form panel" onSubmit={save}><div className="section-title"><h2>记录原币金额，自动折合美元</h2><button className="icon-button" type="button" aria-label="关闭记账" disabled={busy} onClick={()=>setForm(null)}><X size={18}/></button></div><div className="ledger-fields library-fields"><label>发生日期<input type="date" required max={today()} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>币种<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{[["PHP","PHP · 菲律宾比索"],["USD","USD · 美元"],["CREDITS","Codex 额度"],["CNY","CNY · 人民币"],["TWD","TWD · 新台币"],["HKD","HKD · 港币"],["EUR","EUR · 欧元"],["JPY","JPY · 日元"],["GBP","GBP · 英镑"],["SGD","SGD · 新加坡元"],["THB","THB · 泰铢"],["IDR","IDR · 印尼盾"],["MYR","MYR · 马来西亚林吉特"],["KRW","KRW · 韩元"],["AUD","AUD · 澳元"],["CAD","CAD · 加元"],["INR","INR · 印度卢比"],["BRL","BRL · 巴西雷亚尔"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>原始金额<input required type="number" min="0.000001" step="any" inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="例如 250"/></label><label>说明<input maxLength={120} value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="例如：邀请额度消耗、订阅支出"/></label></div><p className="rate-preview">{rate?`${money(Number(form.amount||0)*rate.rate*1e6)} · 1 ${form.currency} = ${rate.rate} USD · 汇率日期 ${rate.date}`:rateError||"正在读取汇率…"}</p><p className="notice">已在自动记录中确认的消耗，不要重复补记。外币按每日参考汇率折算，银行卡的实际结算金额可能不同。</p><button className="library-button primary" type="submit" disabled={busy||!rate}><Check size={16}/>{busy?"保存中…":"保存支出"}</button></form>}
 <section className="ledger-accounts panel"><div className="section-title"><h2>账号额度余额</h2><span>{data?.accounts.length||0} 个账号 · 按邮箱保存</span></div>{data?.accounts.length?data.accounts.map(a=><div className="ledger-account" key={a.id}><span>{a.label}</span><div><strong>{a.unlimited?"不限额度":a.balance===null?"余额未知":`${Number(a.balance).toLocaleString()} 额度 · ${money(Number(a.balance)*40000)}`}</strong><small>已确认消耗 {money(a.confirmed||0)} · 待核实 {money(a.pending||0)}</small></div><time>{date(a.observedAt)}<small>{Date.now()-Date.parse(a.observedAt)>180000?"最后记录 · 切回该账号后更新":"最近已读取"}</small></time></div>):<p className="empty">尚未读取到余额。请在这台电脑登录 Codex，采集器会自动建立记录。</p>}</section>
 <section className="ledger-table-section"><div className="section-title"><h2>自动记录的额度变化</h2><label className="account-filter">最近 100 条<select aria-label="筛选额度账号" value={account} onChange={e=>setAccount(e.target.value)}><option value="">所有账号</option>{data?.accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label></div><div className="ledger-table-wrap"><table className="ledger-table"><thead><tr><th>时间 / 账号</th><th>余额变化</th><th>折合美元</th><th>分类</th></tr></thead><tbody>{data?.changes.map(change=><tr key={change.id}><td>{date(change.observedAt)}<small>{change.accountLabel}</small></td><td>{change.beforeBalance} → {change.afterBalance}<small>{change.direction==="decrease"?"减少":"增加"} {change.amount} 额度</small></td><td>{money(change.usdMicros)}</td><td>{data.canManage&&change.direction==="decrease"?<select aria-label="设置余额减少原因" value={change.classification} disabled={busy} onChange={e=>classify(change.id,e.target.value)}>{["pending","spent","expired","adjustment"].map(value=><option key={value} value={value}>{classification[value]}</option>)}</select>:<span className={change.classification==="pending"?"pending-reason":""}>{classification[change.classification]}</span>}</td></tr>)}</tbody></table>{!data?.changes.length&&<p className="empty">所选账号还没有观察到余额变化。首次余额和重复读取不会记成消费。</p>}</div></section>
 <section className="ledger-table-section"><div className="section-title"><h2>手动记录的支出</h2><span>最近 100 条 · 统一以美元汇总</span></div><div className="ledger-table-wrap"><table className="ledger-table"><thead><tr><th>日期 / 说明</th><th>原币金额</th><th>美元金额</th><th>使用汇率</th>{data?.canManage&&<th>操作</th>}</tr></thead><tbody>{data?.entries.map(entry=><tr key={entry.id}><td>{entry.entryDate}<small>{entry.note||"未填写说明"}</small></td><td>{entry.amount} {entry.currency}</td><td>{money(entry.usdMicros)}</td><td>{entry.rate}<small>{entry.rateDate}</small></td>{data.canManage&&<td>{removeId===entry.id?<button className="delete-confirm" disabled={busy} onClick={()=>remove(entry.id)}>确认删除</button>:<button className="icon-button" aria-label="删除这笔支出" onClick={()=>setRemoveId(entry.id)}><Trash2 size={15}/></button>}</td>}</tr>)}</tbody></table>{!data?.entries.length&&<p className="empty">暂无手动支出。比索等外币金额可以通过“记一笔支出”保存并自动换算。</p>}</div></section>
 <p className="notice">额度折算金额用于你的用量账本，不代表已付现金。自动余额变化无法识别是否来自邀请奖励。外币汇率由 <a href="https://frankfurter.dev/" target="_blank" rel="noopener noreferrer">Frankfurter</a> 提供，保留每笔记录所用汇率和日期，不随之后的汇率变动重算。</p></section>;
}
