"use client";
import { useEffect, useState } from "react";
import { ChevronDown, ExternalLink, Headphones, History, LoaderCircle, Music2, Pause, Play, Search, Volume2 } from "lucide-react";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Slider } from "@/components/ui/slider";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { musicTime, trackKey } from "@/lib/music-types";
import { useMusic } from "./music-provider";
import { useMusicCatalog } from "./music-catalog-provider";

function NamedSlider(props: React.ComponentProps<typeof Slider> & { "aria-label": string }) { return <Slider {...props} ref={node => { node?.querySelector('[role="slider"]')?.setAttribute("aria-label", props["aria-label"]); }}/>; }
export function MusicTransport() {
  const m = useMusic();
  return <div className="music-transport"><button type="button" className="music-button music-primary" disabled={!m.track || m.restoring} aria-label={m.playing || m.loading ? "暂停背景音乐" : "播放背景音乐"} aria-pressed={m.playing} onClick={() => m.playing || m.loading ? m.pause() : void m.play()}>{m.loading ? <LoaderCircle size={18} className="music-loading"/> : m.playing ? <Pause size={18}/> : <Play size={18}/>}<span>{m.loading ? "取消载入" : m.playing ? "暂停" : m.track && m.position > 0 ? "继续播放" : "播放"}</span></button><div className="music-progress"><NamedSlider aria-label="歌曲播放进度" value={[m.position]} min={0} max={m.duration || 1} step={.1} disabled={!m.track || m.loading} onValueChange={v => m.seek(v[0])}/><div><span>{musicTime(m.position)}</span><span>{musicTime(m.duration)}</span></div></div><div className="music-volume"><Volume2 size={18}/><NamedSlider aria-label="音乐音量" value={[m.volume * 100]} min={0} max={100} step={1} onValueChange={v => m.setVolume(v[0] / 100)}/></div></div>;
}
export function MusicSearch({ onSelected }: { onSelected?: () => void }) {
  const m = useMusic();
  const c = useMusicCatalog();
  const { query, provider, submittedQuery, tracks, pending, message, searched, failed, total, nextOffset, search, chooseSource } = c;
  return <div className="music-search-panel"><div className="music-search-source"><label>曲库</label><Select value={provider} onValueChange={value => chooseSource(value as "original" | "netease")}><SelectTrigger aria-label="选择歌曲来源"><SelectValue/></SelectTrigger><SelectContent className="music-source-options"><SelectItem value="original">原音乐站 · music.zkkp.nyc.mn</SelectItem><SelectItem value="netease">网易云备用曲库</SelectItem></SelectContent></Select></div><form className="music-search-form" onSubmit={e => { e.preventDefault(); void search(); }}><label><Search size={17}/><input aria-label="搜索歌曲或歌手" value={query} maxLength={100} onChange={e => c.setQuery(e.target.value)} placeholder="输入歌名或歌手"/></label><button className="music-button" type="submit" disabled={!query.trim() || pending && query.trim() === submittedQuery}>{pending && query.trim() === submittedQuery ? "搜索中" : "搜索"}</button></form>{message && <p className="music-source-message" role={failed ? "alert" : "status"}>{failed && submittedQuery ? `搜索“${submittedQuery}”未完成：` : ""}{message}</p>}{failed && <div className="music-search-recovery"><button className="music-button" onClick={() => void c.retry()} disabled={pending}>重试</button>{provider === "original" && <><a className="music-button" href="https://music.zkkp.nyc.mn/" target="_blank" rel="noopener noreferrer">打开原站<ExternalLink size={14}/></a><button className="music-inline-button" onClick={() => chooseSource("netease")}>查看网易云备用曲库</button></>}</div>}{pending && <p className="music-empty" role="status"><LoaderCircle className="music-loading" size={18}/>正在搜索曲库…</p>}{!pending && searched && !tracks.length && <p className="music-empty">没有找到匹配的歌曲，换个关键词试试。</p>}{!pending && !searched && !failed && <p className="music-empty">{query.trim() ? "点击搜索，读取所选曲库。" : "输入歌名或歌手，搜索所选曲库。"}</p>}{searched && <p className="music-search-summary">“{submittedQuery}”的结果：共 {total} 首匹配，已显示 {tracks.length} 首。受限歌曲仍会显示。</p>}<div className="music-track-list" aria-label="歌曲搜索结果">{tracks.map(song => {
    const selected = m.track && trackKey(song) === trackKey(m.track);
    const restricted = song.availability === "restricted";
    return <div className="music-search-result" key={trackKey(song)}><button className="music-track-row" type="button" disabled={restricted} aria-label={`${restricted ? "播放受限" : "播放"} ${song.name} · ${song.artist}`} aria-current={selected ? "true" : undefined} onClick={() => { void m.play(song, selected ? m.position : 0); onSelected?.(); }}><span className="music-track-icon"><Music2 size={19}/></span><span className="music-track-copy"><strong>{song.name}</strong><small>{song.artist || "歌手未标注"}{song.album ? " · " + song.album : ""}</small><small className="music-track-permission">{restricted ? song.unavailableReason : song.engine === "go-music-dl" ? `原音乐站 · ${song.source}` : "网易云 · 点击播放"}</small></span><span className="music-track-duration">{musicTime(song.duration)}{!restricted && <Play size={15}/>}</span></button>{restricted && <a className="music-official-link" href={`https://music.163.com/#/song?id=${song.id}`} target="_blank" rel="noopener noreferrer" aria-label={`在网易云打开 ${song.name}`}>在网易云打开<ExternalLink size={13}/></a>}</div>;
  })}</div>{nextOffset !== null && <button className="music-button music-load-more" disabled={pending || query.trim() !== submittedQuery} onClick={() => void c.loadMore()}>{pending ? "正在加载" : "加载更多歌曲"}</button>}</div>;
}
export function MusicHistory({ onSelected }: { onSelected?: () => void }) {
  const m = useMusic();
  useEffect(() => { void m.refreshHistory(); }, [m.refreshHistory]);
  return <div className="music-history-panel"><p className="music-history-note">{m.account ? "私人记录随网站管理账号保存。" : "私人记录保存在网站；用这个浏览器回来即可继续。"}</p>{m.storageError && <p className="music-source-message" role="status">{m.storageError}<button className="music-inline-button" onClick={() => void m.refreshHistory()}>重试</button></p>}{!m.history.length && <p className="music-empty">还没有播放记录。选择一首歌开始听，进度会自动保存。</p>}<div className="music-track-list" aria-label="历史播放记录">{m.history.map(entry => <button className="music-track-row music-history-row" type="button" key={trackKey(entry.track)} aria-label={`续播 ${entry.track.name}，从 ${musicTime(entry.position)}`} onClick={() => { void m.play(entry.track, entry.position); onSelected?.(); }}><span className="music-track-icon"><History size={18}/></span><span className="music-track-copy"><strong>{entry.track.name}</strong><small>{entry.track.artist || "歌手未标注"} · 听到 {musicTime(entry.position)} / {musicTime(entry.duration)} · {entry.track.engine === "go-music-dl" ? "原音乐站" : "网易云备用"}</small><span className="music-history-meter"><i style={{ width: `${entry.duration ? Math.min(100, entry.position / entry.duration * 100) : 0}%` }}/></span></span><span className="music-history-date">{new Date(entry.lastPlayedAt).toLocaleDateString("zh-CN", { month: "2-digit", day: "2-digit" })}<Play size={15}/></span></button>)}</div></div>;
}
export default function MusicDock({ onOpenMusic }: { onOpenMusic: () => void }) {
  const m = useMusic(), [open, setOpen] = useState(false), [view, setView] = useState<"search" | "history">("search");
  return <div className="console-music-strip"><div className="pulse-music-dock"><button className={`music-switch ${m.playing ? "is-playing" : ""}`} type="button" aria-pressed={m.playing} aria-label={m.playing || m.loading ? "关闭音乐" : "开启音乐"} disabled={m.restoring} onClick={() => { if (m.playing || m.loading) m.pause(); else if (m.track) void m.play(); else { setView("search"); setOpen(true); } }}>{m.loading ? <LoaderCircle size={17} className="music-loading"/> : <Headphones size={17}/>}<span>音乐{m.playing ? "开" : "关"}</span><i aria-hidden="true"/></button><Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button className="music-dock-button" aria-label="选歌" onClick={() => setView("search")}>选歌<ChevronDown size={14}/></button></PopoverTrigger><button className="music-dock-button" aria-label="查看历史播放" onClick={() => { setView("history"); setOpen(true); }}><History size={16}/><span>历史</span></button><PopoverContent className="pulse-music-popover" role="dialog" aria-label="音乐选歌与播放记录" align="start" sideOffset={10}><div className="music-panel-tabs"><button aria-pressed={view === "search"} onClick={() => setView("search")}><Search size={15}/>选歌</button><button aria-pressed={view === "history"} onClick={() => setView("history")}><History size={15}/>播放历史</button><button className="music-space-link" onClick={() => { setOpen(false); onOpenMusic(); }}>音乐空间<ExternalLink size={14}/></button></div>{view === "search" ? <MusicSearch onSelected={() => setOpen(false)}/> : <MusicHistory onSelected={() => setOpen(false)}/>}</PopoverContent></Popover></div><span className="music-dock-now" title={m.track ? `${m.track.name} · ${m.track.artist}` : undefined}>{m.restoring ? "正在恢复播放记录…" : m.loading ? "正在连接音源…" : m.track ? `${m.track.name} · ${musicTime(m.position)}` : "选一首歌开始听"}</span>{(m.error || m.storageError) && <span className="music-dock-error" role="status">{m.error || "进度尚未同步"}</span>}</div>;
}


