"use client";
import {useEffect,useState} from "react";
import {ExternalLink,FolderArchive,Globe,Plus,Search,Pencil,Trash2,LockKeyhole,Check,X,ChevronDown,Clock3,Smartphone,Monitor} from "lucide-react";
import type {Website} from "@/lib/website-url";
import {websiteTime,type WebsiteBox,type WebsiteEvent} from "@/lib/website-boxes";
import {gameLinks,mobileGameUrl} from "@/lib/game-urls";
function MobileGameLink({url,title,compact=false}:{url:string;title:string;compact?:boolean}){
 const mobile=mobileGameUrl(url,title);
 return mobile?<a className={compact?"box-mobile-link":"box-open box-mobile-link"} href={mobile} target="_blank" rel="noopener noreferrer" aria-label={title+"手机版"}><Smartphone size={15}/>手机版<ExternalLink size={14}/></a>:null;
}
type Result={items:WebsiteBox[];total:number;linkTotal:number;groups:{kind:string;count:number}[];page:number;canManage:boolean;sync:{lastSync:string;phase:string;files:number;scanned:number;saved:number;errors:number}|null};
type Form={url:string;title:string;kind:string;boxName:string;editing:boolean};
function Timeline({box,refresh}:{box:WebsiteBox;refresh:number}){
 const [events,setEvents]=useState<WebsiteEvent[]>([]),[page,setPage]=useState(1),[hasMore,setHasMore]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(""),[retry,setRetry]=useState(0);
 useEffect(()=>{setPage(1);setEvents([]);},[box.id,box.recordCount,refresh]);
 useEffect(()=>{
  const controller=new AbortController();let active=true;setBusy(true);setError("");
  async function load(){try{
   const response=await fetch(`/api/websites/history?box=${encodeURIComponent(box.id)}&page=${page}`,{cache:"no-store",signal:AbortSignal.any([controller.signal,AbortSignal.timeout(12000)])});
   const data=await response.json() as {items:WebsiteEvent[];hasMore:boolean;error?:string};
   if(!response.ok)throw new Error(data.error||"时间线无法读取");
   if(active){setEvents(previous=>page===1?data.items:[...previous,...data.items.filter(item=>!previous.some(old=>old.id===item.id))]);setHasMore(data.hasMore);}
  }catch(e){if(active)setError(e instanceof Error?e.message:"时间线无法读取");}finally{if(active)setBusy(false);}}
  void load();return()=>{active=false;controller.abort();};
 },[box.id,box.recordCount,page,refresh,retry]);
 const labels={delivery:"交付记录",saved:"手动收藏",first:"首次记录",last:"最近记录"};
 return <section className="box-history" aria-label={`${box.title}的时间线`}><h3><Clock3 size={16}/>时间线 <small>由新到旧 · 台北时间 UTC+8</small></h3>
  <ol className="box-timeline">{events.map(event=><li key={event.id}><div className="timeline-stamp"><time dateTime={event.observedAt}>{websiteTime(event.observedAt)}</time><span>{labels[event.recordType]}</span></div><a href={event.url} target="_blank" rel="noopener noreferrer">{event.title}<ExternalLink size={14}/></a><p>{event.url}</p></li>)}</ol>
  {busy&&<p className="box-history-state" role="status">正在读取时间线…</p>}{error&&<p className="box-history-state" role="alert">{error} <button className="library-button" onClick={()=>setRetry(n=>n+1)}>重试</button></p>}
  {!busy&&!error&&!events.length&&<p className="box-history-state">还没有时间记录。</p>}{hasMore&&!busy&&!error&&<button className="library-button box-more" onClick={()=>setPage(n=>n+1)}>查看更早的记录</button>}
 </section>;
}
export default function Websites(){
 const [result,setResult]=useState<Result|null>(null),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[kind,setKind]=useState(""),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[removing,setRemoving]=useState<string|null>(null),[expanded,setExpanded]=useState<Set<string>>(new Set());
 const [form,setForm]=useState<Form|null>(null);
 useEffect(()=>{const timer=setTimeout(()=>{setSearch(query);setPage(1);},300);return()=>clearTimeout(timer);},[query]);
 useEffect(()=>{let active=true,pending=false;const controller=new AbortController();async function load(){if(pending)return;pending=true;try{const response=await fetch(`/api/websites?q=${encodeURIComponent(search)}&kind=${kind}&page=${page}`,{cache:"no-store",signal:AbortSignal.any([controller.signal,AbortSignal.timeout(12000)])});const data=await response.json() as Result & {error?:string};if(!response.ok)throw new Error(data.error||"暂时无法读取收藏");if(active){setResult(data);setError("");}}catch(e){if(active)setError(e instanceof Error?e.message:"连接中断，正在重试");}finally{pending=false;}}void load();const timer=setInterval(load,10000);return()=>{active=false;controller.abort();clearInterval(timer);};},[search,kind,page,refresh]);
 async function save(e:React.FormEvent){e.preventDefault();if(!form)return;setBusy(true);setNotice("");try{const response=await fetch("/api/websites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"操作失败，请重试");setForm(null);setNotice("已保存，所属箱子已更新");setPage(1);setRefresh(n=>n+1);}catch(e){setNotice(e instanceof Error?e.message:"保存失败，请重试");}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);try{const response=await fetch(`/api/websites?id=${id}`,{method:"DELETE"}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"操作失败，请重试");setRemoving(null);setNotice("已移除这条链接，自动采集不会重新添加");setRefresh(n=>n+1);}catch(e){setNotice(e instanceof Error?e.message:"删除失败，请重试");}finally{setBusy(false);}}
 function edit(item:Website){setForm({url:item.url,title:item.title,kind:item.kind,boxName:item.boxName||"",editing:true});setNotice("");}
 const counts=Object.fromEntries((result?.groups||[]).map(group=>[group.kind,group.count])),all=Object.values(counts).reduce((sum,value)=>sum+value,0),sync=result?.sync;
 return <section className="websites-view"><div className="intro"><div><p className="eyebrow">我的网站记录</p><h1>网站收藏 <span className="website-count">{all} 箱</span></h1></div>{result?.canManage?<button className="library-button primary" onClick={()=>{setForm({url:"",title:"",kind:"developed",boxName:"",editing:false});setNotice("");}}><Plus size={16}/>添加网址</button>:<a className="library-button" href="/signin-with-chatgpt?return_to=%2F%23websites" target="_top"><LockKeyhole size={15}/>登录管理</a>}</div>
 <div className="library-status"><span>{result?`${all} 个网站箱子 · ${result.linkTotal} 条收藏链接` : "正在整理网站箱子"} · 同一网站放在一起，展开查看时间线</span><span>{sync?`同步于 ${websiteTime(sync.lastSync)}`:"公开查看 · 云端保存"}</span></div>
 <div className="library-controls"><label className="library-search"><Search size={18}/><input aria-label="搜索收藏的网址、箱子或名称" placeholder="搜索箱子、网站名称或网址…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="library-filters" role="group" aria-label="网站分类">{[["","全部",all],["developed","开发网站",counts.developed||0],["shared","Codex 提供",counts.shared||0]].map(([value,label,count])=><button key={value} aria-pressed={kind===value} onClick={()=>{setKind(String(value));setPage(1);}}>{label}<span>{count}</span></button>)}</div></div>
 <div className="game-link-pairs" aria-label="游戏电脑版与手机版链接">{gameLinks.map(game=><div className="game-link-pair" key={game.name}><strong>{game.name}</strong><div className="game-link-pair-actions"><a className="box-open" href={game.desktop} target="_blank" rel="noopener noreferrer" aria-label={game.name+"本机电脑版"}><Monitor size={15}/>本机电脑版<ExternalLink size={14}/></a><a className="box-open" href={game.mobile} target="_blank" rel="noopener noreferrer" aria-label={game.name+"手机版"}><Smartphone size={15}/>手机版<ExternalLink size={14}/></a></div></div>)}</div>
 {form&&<form className="library-form panel" onSubmit={save}><div className="section-title"><h2>{form.editing?"编辑收藏":"添加网址"}</h2><button type="button" className="icon-button" aria-label="关闭编辑" disabled={busy} onClick={()=>setForm(null)}><X size={18}/></button></div><div className="library-fields"><label>网址<input required type="url" maxLength={2000} placeholder="https://…" value={form.url} disabled={form.editing||busy} onChange={e=>setForm({...form,url:e.target.value})}/></label><label>网站名称<input maxLength={120} placeholder="方便查找的名字" value={form.title} disabled={busy} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>分类<select value={form.kind} disabled={busy} onChange={e=>setForm({...form,kind:e.target.value})}><option value="developed">开发网站</option><option value="shared">Codex 提供</option></select></label><label className="box-name-field">所属箱子<input maxLength={120} list="website-box-names" placeholder="留空，自动按网站归类" value={form.boxName} disabled={busy} onChange={e=>setForm({...form,boxName:e.target.value})}/><small>同一个箱子名称会合并收纳；不同分支可以分别命名。</small></label></div><datalist id="website-box-names">{result?.items.filter(box=>box.id.startsWith("named:")).map(box=><option key={box.id} value={box.title}/>)}</datalist><button className="library-button primary" disabled={busy} type="submit"><Check size={16}/>{busy?"保存中…":"保存"}</button></form>}
 {error&&<p className="library-message" role="alert">{error} <button onClick={()=>setRefresh(n=>n+1)}>重试</button></p>}{notice&&<p className="library-message" role="status">{notice}</p>}
 <div className="website-box-list">{result?.items.map(box=>{const open=expanded.has(box.id),local=/^(localhost|127\.0\.0\.1|\[::1\])(?::|$)/.test(box.address);return <article className={"website-box"+(open?" is-open":"")} key={box.id}><div className="box-heading"><button className="box-toggle" aria-expanded={open} aria-label={`${open?"收起":"展开"}${box.title}的时间线`} onClick={()=>setExpanded(previous=>{const next=new Set(previous);if(next.has(box.id))next.delete(box.id);else next.add(box.id);return next;})}><span className="box-symbol"><FolderArchive size={22}/></span><span className="box-heading-copy"><h2>{box.title}</h2><span>{box.address} · {box.items.length} 条链接 · {box.recordCount} 条时间记录{search&&` · 命中 ${box.matchedCount} 条`}</span></span><ChevronDown size={20} className="box-chevron"/></button><div className="box-open-links"><a className="box-open" href={box.url} target="_blank" rel="noopener noreferrer" aria-label={`打开${box.title}`}>打开网站<ExternalLink size={15}/></a><MobileGameLink url={box.url} title={box.title}/></div></div><div className="box-overview"><span className="box-kind">{box.kind==="developed"?"开发网站":"Codex 提供"}{local&&" · 本机地址"}</span><span>首次 <time dateTime={box.firstSeen}>{websiteTime(box.firstSeen)}</time></span><span>最近 <time dateTime={box.lastSeen}>{websiteTime(box.lastSeen)}</time></span></div>{open&&<div className="box-content"><section className="box-links" aria-label={`${box.title}的收藏链接`}><h3>箱子里的链接</h3>{box.items.map(item=><div className="box-link" key={item.id}><div className="box-link-copy"><div className="box-link-entry"><a href={item.url} target="_blank" rel="noopener noreferrer">{item.title}<ExternalLink size={14}/></a><MobileGameLink url={item.url} title={item.title} compact/></div><p>{item.url}</p><span>首次 {websiteTime(item.firstSeen)} · 最近 {websiteTime(item.lastSeen)}</span></div>{result.canManage&&<div className="website-actions">{removing===item.id?<><button disabled={busy} className="delete-confirm" onClick={()=>remove(item.id)}>确认删除</button><button disabled={busy} className="icon-button" aria-label="取消删除" onClick={()=>setRemoving(null)}><X size={16}/></button></>:<><button disabled={busy} className="icon-button" aria-label={`编辑 ${item.title}`} onClick={()=>edit(item)}><Pencil size={15}/></button><button disabled={busy} className="icon-button" aria-label={`删除 ${item.title}`} onClick={()=>setRemoving(item.id)}><Trash2 size={15}/></button></>}</div>}</div>)}</section><Timeline box={box} refresh={refresh}/></div>}</article>;})}</div>
 {!result&&!error&&<div className="library-empty">正在读取已保存的网站…</div>}{result&&!result.items.length&&<div className="library-empty"><Globe size={28}/><h2>{search||kind?"没有找到匹配的网站":"还没有收藏的网站"}</h2><p>{search||kind?"换个关键词，或查看全部分类。":"采集器会整理本机 Codex 的历史交付链接。以后新回复中的网址也会自动加入。"}</p></div>}
 {result&&result.total>48&&<nav className="library-pagination" aria-label="收藏分页"><button className="library-button" disabled={result.page===1} onClick={()=>setPage(result.page-1)}>上一页</button><span>{result.page} / {Math.ceil(result.total/48)} · {result.total} 个箱子</span><button className="library-button" disabled={result.page*48>=result.total} onClick={()=>setPage(result.page+1)}>下一页</button></nav>}
 <p className="notice">时间线保存每次交付链接的时间与名称，历史链接打开的是该网址当前的内容。收藏公开可见；登录后可调整分类和所属箱子。本机地址需在运行项目的电脑上打开。</p></section>;
}
