import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {deflateSync} from 'node:zlib';
import ts from 'typescript';
const source=path=>readFileSync(new URL(path,import.meta.url),'utf8');
const url=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');
const types=url(source('./compass-types.ts'));
const model=url(source('./compass-workspace.ts').replace("'./compass-types'",JSON.stringify(types)));
const authBase=url(source('./website-api.ts').replace('import { env } from "cloudflare:workers";','const env={OWNER_EMAIL:"owner@example.test"};'));
const auth=url(source('./compass-auth.ts').replace("'./website-api'",JSON.stringify(authBase)));
const png=url(source('./compass-png.ts'));
function route(path){return url(source(path).replace("import { database } from '@/db/raw';","const database=()=>globalThis.fixture;").replace("import { env } from 'cloudflare:workers';","const env={get BUCKET(){return globalThis.bucket;}};").replace("'@/lib/website-api'",JSON.stringify(authBase)).replace("'@/lib/compass-auth'",JSON.stringify(auth)).replace("'@/lib/compass-workspace'",JSON.stringify(model)).replace("'@/lib/compass-png'",JSON.stringify(png)));}
const {GET,POST}=await import(route('../app/api/compass/workspace/route.ts'));
const media=await import(route('../app/api/compass/media/route.ts'));
const {defaultConfig,validConfig,emptyTimer,timerTransition,remaining,mergeConfig}=await import(model);
const {cleanPng}=await import(png);
function fixture(t){const db=new DatabaseSync(':memory:');db.exec(source('../drizzle/0015_glossy_randall_flagg.sql'));db.exec(source('../drizzle/0016_icy_bullseye.sql'));globalThis.fixture={async batch(statements){db.exec("BEGIN");try{const results=[];for(const s of statements)results.push(await s.run());db.exec("COMMIT");return results;}catch(e){db.exec("ROLLBACK");throw e;}},prepare(sql){let args=[];return {bind(...a){args=a;return this;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}};}};}};const objects=new Map();globalThis.bucket={async put(k,b){objects.set(k,b);},async get(k){return objects.has(k)?{body:objects.get(k)}:null;},async delete(k){objects.delete(k);}};t.after(()=>db.close());return {db,objects};}
function req(body,options={}){const headers={'oai-authenticated-user-id':options.id||'test-owner','oai-authenticated-user-email':options.email||'owner@example.test',Origin:options.origin||'https://test.local','Content-Type':options.type||'application/json'};if(options.anonymous){delete headers['oai-authenticated-user-id'];delete headers['oai-authenticated-user-email'];}return new Request('https://test.local/api/compass/workspace'+(options.query||''),{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:options.raw?body:JSON.stringify(body)})});}
async function save(body,options){const r=await POST(req(body,options));return {status:r.status,data:await r.json()};}
async function get(options){return (await GET(req(undefined,options))).json();}
test('all workspace and media endpoints reject anonymous and non-owner; mutations reject foreign origin',async t=>{fixture(t);for(const o of [{anonymous:true},{email:'other@example.test'}]){assert.equal((await GET(req(undefined,o))).status,401);assert.equal((await POST(req({version:0},o))).status,401);assert.equal((await media.GET(req(undefined,o))).status,401);assert.equal((await media.POST(req({},o))).status,401);}assert.equal((await save({version:0},{origin:'https://evil.test'})).status,403);assert.equal((await media.POST(req({}, {origin:'https://evil.test'}))).status,403);});
test('custom section names, labels and full text survive reads, preserve stable IDs, and are account isolated',async t=>{fixture(t);const config=defaultConfig();config.title='我的生活';config.sections[0].name='事业清单';config.sections[0].tags=['写作','重要'];config.habits[1]='晨跑';config.questions[0]='我的问题？';config.sections.push({id:crypto.randomUUID(),name:'我的创意',description:'长内容\n第二段',cover:null,color:'night',tags:['idea']});assert.equal((await save({action:'config',config,version:0})).status,200);assert.deepEqual((await get()).config,config);assert.equal((await get({id:'another-owner'})).config.title,'Compass 今日');assert.equal((await save({action:'config',config,version:0})).status,409);assert.equal((await save({action:'config',config:{...config,title:'新名称'},version:1})).status,200);});
test('invalid names, tags, duplicate IDs, arrays, durations and cross-scope covers are rejected',async t=>{fixture(t);for(const mutate of [c=>c.habits=[],c=>c.title='',c=>c.sections.push(c.sections[0]),c=>c.sections[0].tags=['x'.repeat(25)],c=>c.restSeconds=0,c=>c.focusSeconds=1.5,c=>c.portraits=['x'],c=>c.sections[0].id='__proto__']){const config=defaultConfig();mutate(config);assert.equal(validConfig(config),false);assert.equal((await save({action:'config',config,version:0})).status,400);}const config=defaultConfig();config.sections[0].cover=crypto.randomUUID();assert.equal((await save({action:'config',config,version:0})).status,400);});
test('timer uses absolute timestamps through pause, resume, sleep and completion',()=>{const id=crypto.randomUUID();let timer=timerTransition(emptyTimer(),'start',1000,{seconds:5,phase:'focus',id});assert.equal(remaining(timer,3100),2900);timer=timerTransition(timer,'pause',3100);assert.equal(remaining(timer,900000),2900);timer=timerTransition(timer,'resume',900000);assert.equal(timer.endAt,902900);assert.equal(timerTransition(timer,'finish',902899),null);timer=timerTransition(timer,'finish',999999);assert.equal(timer.status,'finished');assert.equal(timerTransition(timer,'finish',1000000),null);timer=timerTransition(timer,'start',1000000,{seconds:3,phase:'rest',id:crypto.randomUUID()});assert.equal(timer.endAt,1003000);assert.equal(timerTransition(timer,'start',1000000,{seconds:3,phase:'rest',id}),null);});
test('timer API survives reload and only one client can finish or replace a session',async t=>{fixture(t);let now=Date.now();const real=Date.now;Date.now=()=>now;t.after(()=>Date.now=real);let result=await save({action:'timer',command:'start',phase:'focus',seconds:5,id:crypto.randomUUID(),version:0});assert.equal(result.status,200);assert.equal((await get()).timer.endAt,now+5000);assert.equal((await save({action:'timer',command:'pause',version:0})).status,409);now+=5000;const both=await Promise.all([save({action:'timer',command:'finish',version:1}),save({action:'timer',command:'finish',version:1})]);assert.equal(both.filter(r=>r.data.notify).length,1);assert.deepEqual(both.map(r=>r.status).sort(),[200,409]);assert.equal((await get()).timer.status,'finished');});
test('memory CRUD, idempotent create, conflict, completion and remind claims preserve real records',async t=>{fixture(t);const memory={action:'memory',id:crypto.randomUUID(),text:'验收事项\n保留细节',priority:'important',done:false,remindAt:Date.now()-1000,version:0};assert.equal((await save(memory)).status,200);assert.equal((await save(memory)).status,200);assert.equal((await get()).memories.length,1);assert.equal((await save({...memory,text:'changed'})).status,409);const alerts=await Promise.all([save({action:'memory-alert',id:memory.id,version:1}),save({action:'memory-alert',id:memory.id,version:1})]);assert.equal(alerts.filter(r=>r.data.notify).length,1);assert.equal((await save({...memory,text:'修改细节',done:true,version:1})).status,200);assert.equal((await get()).memories[0].text,'修改细节');assert.equal((await get({id:'another-owner'})).memories.length,0);assert.equal((await save({action:'memory-delete',id:memory.id,version:1})).status,409);assert.equal((await save({action:'memory-delete',id:memory.id,version:2})).status,200);assert.equal((await get()).memories.length,0);});
function chunk(type,data){const buf=Buffer.concat([Buffer.from(type),data]);let crc=0xffffffff;for(const b of buf){crc^=b;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}const result=Buffer.alloc(data.length+12);result.writeUInt32BE(data.length);buf.copy(result,4);result.writeUInt32BE((crc^0xffffffff)>>>0,result.length-4);return result;}
function image(width=2,height=2){const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('tEXt',Buffer.from('fixture metadata')),chunk('IDAT',deflateSync(Buffer.alloc((width*4+1)*height))),chunk('IEND',Buffer.alloc(0))]);}
test('upload validates real pixels, strips metadata, stores in R2 and prevents cross-account reads',async t=>{const f=fixture(t);const png=image();const result=await media.POST(req(png,{raw:true,type:'image/png'}));assert.equal(result.status,200);const {id}=await result.json();assert.equal(f.objects.size,1);const response=await media.GET(req(undefined,{query:'?id='+id}));assert.equal(response.status,200);assert.equal(response.headers.get('Content-Type'),'image/png');const stored=Buffer.from(await response.arrayBuffer());assert.equal(stored.includes(Buffer.from('fixture metadata')),false);assert.equal((await media.GET(req(undefined,{query:'?id='+id,id:'other-owner'}))).status,404);const config=defaultConfig();config.portraits[0]=id;config.sections[0].cover=id;assert.equal((await save({action:'config',config,version:0})).status,200);});
test('spoofed PNG, SVG, CRC damage, excessive pixels and unavailable storage fail safely',async t=>{fixture(t);for(const bytes of [Buffer.from('<svg onload="alert(1)"/>'),Buffer.from('<html>'),Buffer.concat([image(),Buffer.from('extra')])]){assert.equal((await media.POST(req(bytes,{raw:true,type:'image/png'}))).status,400);}const bad=image();bad[30]^=1;await assert.rejects(()=>cleanPng(bad));await assert.rejects(()=>cleanPng(image(2401,1)));globalThis.bucket=undefined;assert.equal((await media.POST(req(image(),{raw:true,type:'image/png'}))).status,503);globalThis.fixture={prepare(){throw new Error('offline');}};assert.equal((await GET(req())).status,503);assert.equal((await save({action:'config',config:defaultConfig(),version:0})).status,503);});
test('unseen alerts survive response loss until explicit acknowledgement and retain the completed phase',async t=>{fixture(t);let now=Date.now();const real=Date.now;Date.now=()=>now;t.after(()=>Date.now=real);await save({action:'timer',command:'start',phase:'focus',seconds:1,id:crypto.randomUUID(),version:0});now+=1000;await save({action:'timer',command:'finish',version:1});await save({action:'timer',command:'start',phase:'rest',seconds:3,id:crypto.randomUUID(),version:2});let state=await get();assert.equal(state.timer.phase,'rest');assert.equal(state.alerts.length,1);assert.match(state.alerts[0].text,/专注完成/);assert.equal((await get()).alerts.length,1);await save({action:'ack-alert',id:state.alerts[0].id,version:0});assert.equal((await get()).alerts.length,0);});
test('due reminders are not hidden by the 500 most recent display records',async t=>{const {db}=fixture(t);await save({action:'memory',id:crypto.randomUUID(),text:'old due reminder',priority:'important',done:false,remindAt:Date.now()-1000,version:0});const scope=db.prepare('SELECT scope FROM compass_memories').get().scope;const insert=db.prepare('INSERT INTO compass_memories(scope,id,text,priority,done,remind_at,notified,version,created) VALUES(?,?,?,?,0,NULL,0,1,?)');for(let i=0;i<501;i++)insert.run(scope,crypto.randomUUID(),'new '+i,'normal',Date.now()+i+1000);const state=await get();assert.equal(state.memories.length,500);assert.equal(state.memories.some(m=>m.text==='old due reminder'),false);assert.equal(state.dueMemories[0].text,'old due reminder');});
test('config rebase retains local edits and unrelated remote edits plus new custom cards',()=>{const base=defaultConfig(),draft=structuredClone(base),latest=structuredClone(base);draft.sections[0].name='local name';latest.sections[0].description='remote description';latest.title='remote title';latest.sections.push({id:crypto.randomUUID(),name:'remote card',description:'',color:'sage',tags:[],cover:null});const merged=mergeConfig(base,draft,latest);assert.equal(merged.sections[0].name,'local name');assert.equal(merged.sections[0].description,'remote description');assert.equal(merged.title,'remote title');assert.equal(merged.sections.length,7);assert.equal(validConfig(merged),true);});
test('deleting a memory cancels its queued reminder but a stale deletion does not',async t=>{fixture(t);const id=crypto.randomUUID();await save({action:'memory',id,text:'cancel me',priority:'normal',done:false,remindAt:Date.now()-1000,version:0});await save({action:'memory-alert',id,version:1});assert.equal((await get()).alerts.length,1);assert.equal((await save({action:'memory-delete',id,version:0})).status,409);assert.equal((await get()).alerts.length,1);await save({action:'memory-delete',id,version:1});assert.equal((await get()).alerts.length,0);});

