import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';

function moduleUrl(source){return 'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');}
const types=moduleUrl(readFileSync(new URL('./compass-types.ts',import.meta.url),'utf8'));
const auth=moduleUrl(readFileSync(new URL('./website-api.ts',import.meta.url),'utf8').replace('import { env } from "cloudflare:workers";','const env={OWNER_EMAIL:"owner@example.test"};'));
const store=moduleUrl(readFileSync(new URL('./compass-store.ts',import.meta.url),'utf8').replace("import { database } from '@/db/raw';","const database=()=>globalThis.compassFixture;").replace("'./compass-types'",JSON.stringify(types)));
const route=moduleUrl(readFileSync(new URL('../app/api/compass/route.ts',import.meta.url),'utf8').replace("import { database } from '@/db/raw';","const database=()=>globalThis.compassFixture;").replace("'@/lib/website-api'",JSON.stringify(auth)).replace("'@/lib/compass-types'",JSON.stringify(types)).replace("'@/lib/compass-store'",JSON.stringify(store)));
const {GET,POST}=await import(route);
const {validCompassDate}=await import(types);
const date='2026-09-30',origin='https://fixture.test';
function fixture(t){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../drizzle/0014_serious_jetstream.sql',import.meta.url),'utf8'));globalThis.compassFixture={prepare(sql){let args=[];return {bind(...values){args=values;return this;},async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}};}};t.after(()=>sqlite.close());return sqlite;}
function request(body,options={}){const headers={'oai-authenticated-user-id':options.id||'owner-id','oai-authenticated-user-email':options.email||'owner@example.test',...(body?{Origin:options.origin||origin,'Content-Type':'application/json'}:{})};if(options.anonymous){delete headers['oai-authenticated-user-id'];delete headers['oai-authenticated-user-email'];}return new Request(origin+'/api/compass?date='+(options.date||date),{method:body?'POST':'GET',headers,...(body?{body:JSON.stringify({date,...body})}:{})});}
async function save(body,options){const response=await POST(request(body,options));return {status:response.status,data:await response.json()};}
test('private API rejects anonymous, non-owner and cross-origin writes',async t=>{fixture(t);for(const options of [{anonymous:true},{email:'visitor@example.test'}]){assert.equal((await GET(request(null,options))).status,401);assert.equal((await POST(request({action:'habit',index:0,value:true,version:0},options))).status,401);}assert.equal((await save({action:'habit',index:0,value:true,version:0},{origin:'https://other.test'})).status,403);const response=await GET(request());assert.match(response.headers.get('cache-control'),/no-store/);});
test('journal and task retries are idempotent; changed payload with same ID conflicts',async t=>{fixture(t);for(const action of ['entry','task']){const body={action,id:crypto.randomUUID(),kind:'Journal',text:'Fixture only',due:null};assert.equal((await save(body)).status,200);assert.equal((await save(body)).status,200);assert.equal((await save({...body,text:'Changed'})).status,409);}const state=await (await GET(request())).json();assert.equal(state.entries.length,1);assert.equal(state.tasks.length,1);});
test('independent journal writes both survive; dates isolate entries and keep global tasks',async t=>{fixture(t);await Promise.all(['A','B'].map(text=>save({action:'entry',id:crypto.randomUUID(),kind:'Wins',text})));await save({action:'task',id:crypto.randomUUID(),text:'Across days'});const today=await (await GET(request())).json(),other=await (await GET(request(null,{date:'2026-09-29'}))).json();assert.equal(today.entries.length,2);assert.equal(other.entries.length,0);assert.equal(other.tasks.length,1);});
test('daily CAS prevents stale overwrites and retries explicit desired values safely',async t=>{fixture(t);assert.equal((await save({action:'habit',index:1,value:true,version:0})).status,200);assert.equal((await save({action:'habit',index:1,value:true,version:0})).status,200);assert.equal((await save({action:'habit',index:1,value:false,version:0})).status,409);assert.equal((await save({action:'scores',scores:[7,null,8,null,null,10],version:0})).status,409);const saved=await save({action:'scores',scores:[7,null,8,null,null,10],version:1});assert.equal(saved.status,200);assert.equal(saved.data.day.habits[1],true);assert.deepEqual(saved.data.day.scores,[7,null,8,null,null,10]);assert.equal((await save({action:'scores',scores:[7,null,8,null,null,10],version:1})).status,200);});
test('tasks use individual versions and explicit completion; account scope cannot be switched by body',async t=>{fixture(t);const id=crypto.randomUUID();await save({action:'task',id,text:'Task'});assert.equal((await save({action:'toggle',id,done:true,version:1})).status,200);assert.equal((await save({action:'toggle',id,done:true,version:1})).status,200);assert.equal((await save({action:'toggle',id,done:false,version:1})).status,409);assert.equal((await save({action:'toggle',id,done:false,version:2})).status,200);const other=await (await GET(request(null,{id:'other-owner-id'}))).json();assert.equal(other.tasks.length,0);assert.equal((await save({action:'toggle',id,scope:'owner-id',done:true,version:3},{id:'other-owner-id'})).status,409);});
test('invalid scores, kinds, dates, oversized content and bad habit indices never write',async t=>{fixture(t);for(const value of [0,11,1.5,'5'])assert.equal((await save({action:'scores',scores:[value,null,null,null,null,null],version:0})).status,400);for(const index of [-1,3,'1'])assert.equal((await save({action:'habit',index,value:true,version:0})).status,400);for(const d of ['2026-02-30','2026-13-01','2026-9-30']){assert.equal(validCompassDate(d),false);assert.equal((await GET(request(null,{date:d}))).status,400);}for(const kind of ['__proto__','unknown'])assert.equal((await save({action:'entry',id:crypto.randomUUID(),text:'x',kind})).status,400);assert.equal((await save({action:'task',id:crypto.randomUUID(),text:'x'.repeat(4001)})).status,400);});
test('unavailable storage gives a recoverable error without a false saved response',async t=>{fixture(t);globalThis.compassFixture={prepare(){throw new Error('offline');}};assert.equal((await GET(request())).status,503);assert.equal((await save({action:'task',id:crypto.randomUUID(),text:'Retained draft'})).status,503);});
