import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createLocationSession,distanceMeters,bearingDegrees} from '../geo-utils.mjs';
import {createTripRecorder,STAY_MS,readTrips,saveTrips,tripTime,tripDuration} from '../travel-history.mjs';
import {createTravelRouter} from '../travel-routing.mjs';
import {travelPlaces} from '../travel-data.mjs';
assert.equal(Math.round(bearingDegrees([118,24],[118,25])),0);assert.ok(distanceMeters([118,24],[118.001,24])>100);
let now=100000,success,failure,cleared=[],state;
const geo={watchPosition(ok,bad){success=ok;failure=bad;return 0;},clearWatch(id){cleared.push(id);}};
const session=createLocationSession({geolocation:geo,onChange:s=>state=s,bbox:[118,24,119,25],now:()=>now});
assert.equal(session.getState().enabled,false);session.start();success({timestamp:now,coords:{longitude:118.2,latitude:24.2,accuracy:5,heading:0,speed:2}});assert.equal(state.heading,0);assert.equal(state.trail.length,1);
now+=2000;success({timestamp:now,coords:{longitude:118.2004,latitude:24.2,accuracy:5,heading:null,speed:2}});assert.equal(state.trail.length,2);
now+=31000;session.tick();assert.equal(state.status,'stale');session.stop();assert.equal(state.trail.length,0);success({timestamp:now,coords:{longitude:118.2,latitude:24.2,accuracy:5}});assert.equal(state.position,null);assert.ok(cleared.includes(0));
session.start();failure({code:1});assert.equal(state.status,'denied');assert.equal(state.enabled,false);
session.start();success({timestamp:now,coords:{longitude:120,latitude:25,accuracy:5}});assert.equal(state.status,'outside');assert.equal(state.trail.length,0);
session.suspend();assert.equal(state.status,'suspended');session.resume();assert.equal(state.status,'requesting');session.stop();
const p={id:'site',name:'测试景点',ll:[118.06,24.45]},rec=createTripRecorder({places:[p]}),start=Date.UTC(2026,8,28,0,0,0);
rec.feed({ll:p.ll,accuracy:5,at:start});rec.feed({ll:p.ll,accuracy:5,at:start+11000});
assert.equal(rec.getTrip().events.filter(e=>e.type==='arrive').length,1);assert.equal(rec.getTrip().events.find(e=>e.type==='arrive').at,start);
for(let t=start+30000;t<=start+STAY_MS+60000;t+=30000)rec.feed({ll:p.ll,accuracy:5,at:t});
assert.equal(rec.getTrip().events.filter(e=>e.type==='stay').length,1);assert.equal(rec.getTrip().events.find(e=>e.type==='stay').at,start+STAY_MS);
rec.feed({ll:[118.063,24.45],accuracy:5,at:start+STAY_MS+90000});rec.feed({ll:[118.063,24.45],accuracy:5,at:start+STAY_MS+101000});assert.equal(rec.getTrip().events.filter(e=>e.type==='leave').length,1);
rec.pause(start+STAY_MS+110000);rec.feed({ll:p.ll,accuracy:5,at:start+STAY_MS+3600000});assert.equal(rec.getTrip().events.filter(e=>e.type==='stay').length,1);assert.equal(rec.getTrip().track.at(-1).breakBefore,true);
rec.stop(start+STAY_MS+3620000);assert.ok(rec.getTrip().endedAt);
const memory=new Map(),storage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)};saveTrips(storage,[rec.getTrip()]);assert.equal(readTrips(storage).length,1);assert.equal(tripDuration(61500),'1分 1秒');assert.match(tripTime(start),/08:00:00/);
const rec2=createTripRecorder({places:[p]});rec2.feed({ll:p.ll,accuracy:65,at:start});rec2.feed({ll:p.ll,accuracy:65,at:start+30000});assert.equal(rec2.getTrip().events.filter(e=>e.type==='arrive').length,0);
const router=createTravelRouter(JSON.parse(fs.readFileSync('public/data/travel-network.json'))),a=travelPlaces.find(p=>p.id==='longtou'),b=travelPlaces.find(p=>p.id==='sanqiutian');assert.ok(router.walk(a.ll,b.ll).points.length>2);assert.ok(router.walk([121,25],b.ll).error);
console.log('PASS: location lifecycle, accuracy, denial, stale callbacks, routes, arrival/departure, 20-minute stay, background gaps, date/time, local storage.');
