import {islandExtras} from './island-catalog.mjs';
export const checkedOn='2026-09-28';
export const sources={
  trinity:['三一堂公共导览','https://kulangsuisland.org/trinity-church-kulangsu-gulangyu/'],
  trinityMap:['三一堂坐标与照片档案','https://commons.wikimedia.org/wiki/Category:Trinity_Church,_Gulangyu'],
  guide:['鼓浪屿管委会公共旅游导览（历史资料）','https://kulangsuisland.org/experience-kulangsu-introducing-four-cultural-heritage-routes-including-a-detailed-road-map/'],
  beaches:['鼓浪屿公园与沙滩导览','https://kulangsuisland.org/southern-parks-beaches/'],
  meihua:['美华沙滩导览','https://kulangsuisland.org/mei-hua-beach-kulangsu-gulangyu/'],
  palace:['故宫鼓浪屿外国文物馆','https://www.gggly.org.cn/index/visit'],
  osm:['地点坐标：OpenStreetMap / OpenFreeMap','https://www.openstreetmap.org/copyright'],
  island:['鼓浪屿文化旅游发展中心','https://www.glyylq.cn/survey.php'],
  garden:['菽庄花园官方介绍','https://www.glyylq.cn/article.php?id=157'],
  hours:['景区开放公告','https://www.glyylq.cn/article.php?id=1265'],
  heritage:['鼓浪屿世界遗产档案','https://whc.unesco.org/en/list/1541/'],
  mansion:['鼓浪屿建筑文化资料','https://www.xmrd.gov.cn/rdlz/dbjygk/jyhfh/201703/t20170314_5053183.htm'],
  oldTown:['中山路历史街区保护资料','https://www.xmrd.gov.cn/rdlz/jdgz/202410/t20241002_238297.htm'],
  market:['厦门地方志：八市','https://xm.fjdsfzw.org.cn/2024-09-02/content_145949.html'],
  streets:['中山路历史文化街区','https://news.xmnn.cn/xmxw/202501/t20250122_294565.html'],
  ferry:['轮渡游客乘船指南','https://xmferry.com/wybm/wshlk/xchgpp/index.htm'],
  ferryUpdate:['2026年9月21日起航班调整','https://xmferry.com/xwzx/zxgg/32717.htm'],
  pianoPier:['钢琴码头官方航线','https://xmferry.com/mtjjt/gqmt/hxjpj/index.htm'],
  terminals:['轮渡码头介绍','https://www.xmferry.com/xwzx/chbfc/mtfc/'],
  ticket:['轮渡官网与当日公告','https://xmferry.com/']
};

// WGS84 positions from the existing OpenFreeMap/OSM snapshot. They are visit
// reference points, not surveyed ticket gates or guaranteed accessible entrances.
export const travelPlaces=[
 ...islandExtras,
 {id:'gangqin',name:'钢琴码头',area:'ferry',island:true,ll:[118.06828737258911,24.448741588470668],kind:'居民专线 / 通宵航线',duration:'按当日航线与资格乘船',source:['pianoPier','terminals'],
  intro:'位于鼓浪屿东侧，靠近鹿礁路。码头建筑外形像打开的三角钢琴，和东北侧的三丘田码头不是同一处。',
  highlights:['主要涉及居民专线，另有官方公布的通宵航线，不能当作普通游客白天默认登岛口。','附近可衔接龙头路、海底世界与东岸街巷。'],tips:'地图点位依据钢琴码头附近的OSM标识牌，仅供辨认片区，并非实测检票闸机。乘船资格、通宵航班和临时调整以官方及现场为准。'},
 {id:'songyu',name:'嵩屿客运码头（嵩鼓码头）',area:'ferry',ll:[118.04162085056305,24.45718958877957],kind:'海沧出发 / 公共交通换乘',duration:'按票面预留候船时间',source:['terminals','ferry'],walkingUnavailable:true,
  intro:'位于海沧区，与厦门岛内的东渡、第一码头分处海湾两侧。现有地图快照使用“嵩鼓码头”名称，轮渡官方使用“嵩屿客运码头”。',
  highlights:['官方介绍包括至鼓浪屿内厝澳的旅游客运航线，以及至第一码头的海上公共交通航线。','前往鼓浪屿时应核对目的地、船票与候船区，不把它与嵩屿货运港区混为一处。'],tips:'此片区尚未接入连续步行路网，暂不生成到这里的步行路线；可查看地图位置与官方乘船资料。点位不是实测检票入口。'},
 {id:'sanqiutian',name:'三丘田码头',area:'ferry',island:true,ll:[118.064704,24.452844],kind:'登岛与返程',photo:'sanqiutian',duration:'预留候船时间',source:['ferry','ticket'],
  intro:'靠近鼓浪屿东北侧的游客码头，是从东渡上岛后展开老别墅与街巷游览的一个起点。先辨认返程候船区，再开始岛上步行，会比临近离岛时找码头从容。',
  highlights:['往岛内走可接八卦楼、龙头路一带；不必一下船就横穿到最远的景点。','返程目的码头有日夜差异。住中山路附近，也不能默认每个时段都直达中山路对岸。'],tips:'请核对船票上的日期、出发码头与航次。岛上景区门票不等于往返船票。'},
 {id:'neicuo',name:'内厝澳码头',area:'ferry',island:true,ll:[118.053696,24.449074],kind:'西侧登岛口',photo:'neicuo',duration:'预留候船时间',source:['ferry','ferryUpdate'],
  intro:'位于鼓浪屿西侧，适合作为从海边和安静街巷开始的入口。它和三丘田不在同一侧，不能把两者当作一个码头。',
  highlights:['上岛后可沿岛内道路慢慢走向日光岩、港仔后与菽庄花园。','去第一码头、东渡等方向的航线要逐一核对，不能凭“回厦门”判断登船口。'],tips:'内厝澳至第一码头游客航线已发布2026年9月21日起调整公告，具体航次打开官方公告确认。'},
 {id:'sunlight',name:'日光岩',area:'island',island:true,ll:[118.062247,24.444615],kind:'登高观景',photo:'sunlight',duration:'建议 60–90 分钟',source:['island','hours'],
  intro:'鼓浪屿中部偏南的登高景点。亮点在于石阶、岩壁与高处的海岛视野：红瓦、绿树、曲折岸线和厦门岛天际线，可以放在同一幅画面里。',
  highlights:['先看山脚与岩壁，再上观景平台，避免只把它当作一次登顶打卡。','顶部空间与阶梯有限；拍摄时不要堵住通道，体力不够可缩短登高段。'],tips:'这一站台阶较多。建议和菽庄花园分配好体力，遇雷雨、大风或临时管制按现场要求调整。'},
 {id:'shuzhuang',name:'菽庄花园',area:'island',island:true,ll:[118.064511,24.441675],kind:'滨海园林',photo:'shuzhuang',duration:'建议 60–90 分钟',source:['garden','hours'],
  intro:'在港仔后海边把庭院、假山、桥廊和海景组织在一起的园林。游览重点是“从园中看海”的视线变化，而不是直奔最靠海的一处。',
  highlights:['沿曲桥和庭院慢行，比较门洞、栏杆与远处海面构成的不同景框。','后山听涛轩有钢琴博物馆，可把建筑、园林与音乐收藏放在一起看。'],tips:'桥面和沿海石阶雨后可能湿滑。开放时间及演奏讲解可能调整，以景区官方当日安排为准。'},
 {id:'piano',name:'鼓浪屿钢琴博物馆',area:'island',island:true,ll:[118.064833,24.441470],kind:'音乐收藏',photo:'piano',duration:'建议 30–45 分钟',source:['garden','hours'],
  intro:'位于菽庄花园听涛轩，是理解鼓浪屿音乐文化的一站。看点是不同年代钢琴的结构、造型与陈设，不只是建筑外观。',
  highlights:['把它和菽庄花园合并安排，减少在同一片区反复折返。','想听演奏或讲解，要查看馆方当天公布的场次，不把网上旧时刻当成预约。'],tips:'它是钢琴博物馆，不是八卦楼内的风琴博物馆。馆内拍摄与参观秩序听从工作人员安排。'},
 {id:'haoyue',name:'皓月园',area:'island',island:true,ll:[118.071222,24.443897],kind:'海岸与纪念景观',photo:'haoyue',duration:'建议 40–60 分钟',source:['island','hours'],
  intro:'鼓浪屿东南侧临海的纪念园林，郑成功塑像与岩岸构成鲜明的轮廓。这里更适合近看石刻、园林和对岸海景，与日光岩的高处俯瞰不同。',
  highlights:['先沿海边看塑像和岩石之间的关系，再进入园内细看纪念性景观。','可与毓园、海天堂构串联成岛东南的一段步行，不必再绕回岛西。'],tips:'海边风大时注意帽子与随身物品，不越过护栏靠近岩岸。'},
 {id:'bagua',name:'八卦楼 · 风琴博物馆',area:'island',island:true,ll:[118.063207,24.450138],kind:'建筑与风琴',photo:'bagua',duration:'建议 45–60 分钟',source:['island','hours','heritage'],
  intro:'鼓浪屿具有辨识度的穹顶建筑。适合先从外部看屋顶、柱廊和立面，再进入风琴收藏主题；建筑本身和展品是两条不同的参观线索。',
  highlights:['沿外墙变化角度，看穹顶与周围坡地、老别墅的关系。','风琴与钢琴不是同一种乐器；可与菽庄花园的钢琴博物馆形成对照。'],tips:'八卦楼风琴博物馆与管风琴艺术中心不是同一个地点，购票时核对完整名称。'},
 {id:'haitiantang',name:'海天堂构',area:'island',island:true,ll:[118.067697,24.445670],kind:'中西合璧建筑',photo:'haitiantang',duration:'建议 40–60 分钟',source:['mansion','heritage'],
  intro:'鼓浪屿老别墅群中的建筑文化节点。观察重点是传统屋顶、立面装饰和西式建筑构件如何组合，而不是把它当成又一栋同样的洋楼。',
  highlights:['先看屋顶轮廓，再看门窗、柱式和庭院的尺度。','可与周围福建路街巷、毓园串联，放慢步速看建筑细节。'],tips:'院内展览、表演或收费项目可能单独管理；开放范围以现场为准，不承诺固定演出。'},
 {id:'yuyuan',name:'毓园 · 林巧稚纪念园',area:'island',island:true,ll:[118.068051,24.443345],kind:'人物与纪念园',photo:'yuyuan',duration:'建议 20–40 分钟',source:['island','hours'],
  intro:'与林巧稚相关的人物纪念空间。与热闹的商业街相比，这里适合停下来读人物生平、看看园林，给一整天的步行留一段安静时间。',
  highlights:['把人物故事和园内纪念陈设一起看，而不是只拍一张入口照片。','位置适合连接皓月园与海天堂构，不必为这一站单独横穿全岛。'],tips:'纪念园与室内纪念馆的开放范围可能不同，进入室内展区前查看现场公告。'},
 {id:'beach',name:'港仔后沙滩',area:'island',island:true,ll:[118.062022,24.441914],kind:'海滩停留',photo:'beach',duration:'建议 20–40 分钟',source:['island','garden'],
  intro:'位于日光岩南侧、菽庄花园附近的海滨空间。它适合在园林或登高之后放慢节奏，看海面、沙滩和岸边建筑的层次。',
  highlights:['可接在日光岩或菽庄花园之后，作为一段休息与观景停留。','海潮、光线和天气会改变岸线观感，照片不是当天海况。'],tips:'这里的地图标注不代表安全泳区；是否可下水、开放范围与救生值守，以现场规定为准。'},
 {id:'longtou',name:'龙头路街巷',area:'island',island:true,ll:[118.065945,24.447389],kind:'街巷与小吃',photo:'longtou',duration:'建议 45–75 分钟',source:['heritage'],
  intro:'把鼓浪屿建筑漫步与用餐休息衔接起来的街巷片区。除了主街店铺，也可以看看转角、门窗和坡道，感受岛上街道的尺度。',
  highlights:['把小吃作为途中补给，不必在同一餐里把所有种类都买齐。','从主街分散到相邻小巷，但不要进入私人院落或影响居民生活。'],tips:'商家、营业时间与价格变化较快；本图不推荐未核验的“必吃店”，消费前确认标价。'},
 {id:'zhongshan',name:'中山路骑楼步行街',area:'oldtown',ll:[118.0736517906189,24.45645224252944],kind:'骑楼与夜景',photo:'zhongshan',duration:'建议 60–120 分钟',source:['streets','oldTown'],
  intro:'这是一段可以慢走的历史商业街，而不是单个建筑。骑楼廊下、连续立面、街口与支巷，构成中山路最值得观察的细节。',
  highlights:['从靠海一端向街内走，对比老建筑上层立面与一层店铺。','傍晚可同时看白天的建筑细节和入夜后的灯光，不必只在最拥挤的主街停留。'],tips:'建议接在鼓浪屿返程之后，但先确认船实际返回哪个码头；东渡返程需另接交通到中山路。'},
 {id:'zhenbang',name:'镇邦路街区',area:'oldtown',ll:[118.07091057300568,24.45736049623469],kind:'支巷与闽南生活',photo:'zhenbang',duration:'建议 25–45 分钟',source:['streets'],
  intro:'中山路周边可以转进去慢逛的街巷。比起只看主街招牌，这里适合观察转角、骑楼、沿街店铺与邻里生活的连接。',
  highlights:['与中山路主街搭配游览，让行程从一条直线变成一段老城散步。','建筑和商业更新同时存在，可以比较新店面与旧街巷的关系。'],tips:'这是街区参考点，不是某一家店的位置；营业与活动信息以现场为准。'},
 {id:'bashi',name:'八市 · 第八市场',area:'oldtown',ll:[118.069709,24.460954],kind:'市场与海鲜',photo:'bashi',duration:'建议 45–75 分钟',source:['market'],
  intro:'厦门老城的日常市场片区，海鲜摊、食材、小吃与居民买菜的动线交织在一起。这里的看点是正在发生的生活，不是一个封闭景区。',
  highlights:['留意不同摊位的海产与食材，沿街走一圈再决定吃什么。','和中山路相比，八市更偏向市场生活，可安排在下午较早时段，再去骑楼街区。'],tips:'地面可能潮湿，人多时收好随身物品。海鲜消费先问清计价单位、重量与加工费。'},
 {id:'xinjie',name:'新街礼拜堂',area:'oldtown',ll:[118.077326,24.456091],kind:'老城建筑',photo:'xinjie',duration:'建议 15–30 分钟',source:['oldTown','streets'],
  intro:'中山路周边的宗教建筑节点。可把立面、柱廊和周围街巷放在一起观察，感受老城中不同建筑用途与风格的并存。',
  highlights:['以外观欣赏为基础，不把宗教活动空间当成随意拍摄的景区。','与骑楼主街形成建筑风格对照，适合建筑爱好者短暂停留。'],tips:'开放和礼拜活动以现场安排为准，进入前征得允许；不干扰宗教活动。'},
 {id:'lujiang',name:'鹭江道滨海步行段',area:'oldtown',ll:[118.06914,24.4558],kind:'海湾与对岸视野',photo:'lujiang',duration:'建议 20–40 分钟',source:['streets','ferry'],
  intro:'靠近中山路海侧的滨海散步段，可以隔海看鼓浪屿。它适合作为老城散步的开头或结尾，也能帮助你理解码头、海峡与岛屿的位置。',
  highlights:['看海时把鼓浪屿的地标与白天在岛上的经历对应起来。','前往码头时走正式过街设施，不沿车辆通道横穿。'],tips:'临海步道不等于码头候船区。赶船时请按票面导航到具体客运入口。'},
 {id:'dongdu',name:'东渡客运码头（厦鼓码头）',area:'ferry',ll:[118.069752,24.482735],kind:'日间游客出发',photo:'dongdu',duration:'按票面预留安检时间',source:['ferry','ticket'],
  intro:'位于东渡、靠近国际邮轮中心的游客登岛码头。它不在中山路对面，从中山路出发要另外安排市内交通。',
  highlights:['日间游客航线可到三丘田或内厝澳，购票时根据岛上游览起点选择。','到站后认准游客客运及检票指引，不把国际邮轮业务入口当成鼓浪屿检票口。'],tips:'导航可搜索东渡客运码头/厦鼓码头。到达时间、检票要求和票价以票面及官方公告为准。'},
 {id:'lundu',name:'厦门轮渡码头 · 2号厅',area:'ferry',ll:[118.068207,24.457365],kind:'夜间游客航线',photo:'lundu',duration:'依当日夜航安排',source:['ferry','ticket'],
  intro:'靠近中山路的老轮渡码头。对游客而言，重点是2号厅的夜间旅游航线；不要因为它离中山路近，就把它当成白天游客登岛的默认入口。',
  highlights:['夜间游客可按官方公布的时段前往三丘田，季节转换会影响首班时间。','中山路与这里步行衔接方便，但返程目的码头仍须逐班确认。'],tips:'本站不缓存航班表。居民专线与游客航线区分购票，具体班次以轮渡官方当日信息为准。'},
 {id:'diyi',name:'第一码头客运站',area:'ferry',ll:[118.06656,24.463996],kind:'替代航线与返程',photo:'diyi',duration:'按具体航线安排',source:['ferry','ferryUpdate'],
  intro:'与厦门轮渡码头、东渡客运码头不同的客运节点。可在核对航线之后作为登岛方案或返程衔接点，不要只凭“轮渡”二字前往。',
  highlights:['第一码头至内厝澳的游客航线，与经嵩屿换乘是不同方案。','从这里可衔接八市老城散步，但请先查清所买船票对应的码头。'],tips:'2026年9月已有内厝澳至第一码头航班调整；以最新公告和售票系统为准。'}
];

travelPlaces.find(p=>p.id==='sunlight').access=[118.063320,24.445328];
export const travelRoutes=[
 {id:'coastal',name:'小公园与南岸海景',estimate:'建议分段慢游，按体力删减',stops:['neicuo','junru','tingtao','gusheng','beach','yanping','shuzhuang','guanhai-beach','yuyuan','dadeji','haoyue'],note:'经过西南岸小景、延平公园和多处海滩。收费园区可选择进入或绕开；不代表连续无台阶的环岛道路。'},
 {id:'north',name:'岛北建筑与音乐',estimate:'建议半日，馆内停留另计',stops:['sanqiutian','us-consulate','customs-tower','palace','yanwei','hsbc','organ-center','bagua','trinity','yin-house'],note:'包含坡道、历史旧址与仍在使用的建筑。私人院落仅看外观，展馆需核对开放。'},
 {id:'classic',name:'鼓浪屿经典一日',estimate:'建议 5–7 小时，含停留，不含候船',stops:['sanqiutian','bagua','sunlight','beach','shuzhuang','piano','yuyuan','haoyue','haitiantang','longtou','sanqiutian'],note:'有登高与台阶。体力有限时删去日光岩登顶或减少馆内停留，不必全部打卡。'},
 {id:'gentle',name:'建筑与音乐慢游',estimate:'建议 3–4 小时，不含候船',stops:['sanqiutian','bagua','longtou','haitiantang','yuyuan','sanqiutian'],note:'少一段登顶，但岛上仍有坡道与台阶；不是无障碍路线。'},
 {id:'evening',name:'中山路与八市',estimate:'建议 2–3 小时，含用餐停留',stops:['diyi','bashi','lundu','lujiang','zhenbang','zhongshan','xinjie'],note:'可从第一码头或老轮渡附近接入。若船返回东渡，先另接市内交通。'}
];
export const ferryOptions={
 day:{name:'日间 · 东渡—三丘田',from:'dongdu',to:'sanqiutian',via:[[118.0645,24.481],[118.0598,24.468],[118.0618,24.4566]],note:'日间游客航线示意。按已购航次乘船，不代表即时班次或船舶航迹。'},
 night:{name:'夜间 · 轮渡2号厅—三丘田',from:'lundu',to:'sanqiutian',via:[[118.067,24.4558]],note:'仅用于夜间游客方案，需核对季节时段；不是日间登岛方案。'},
 west:{name:'第一码头—内厝澳',from:'diyi',to:'neicuo',via:[[118.060,24.462],[118.0518,24.456]],note:'游客航线示意；票务与2026年9月21日起航班调整见官方公告。'}
};
