import { sqliteTable, text, integer, index, primaryKey } from "drizzle-orm/sqlite-core";
export const microphoneRooms=sqliteTable('microphone_rooms',{id:text('id').primaryKey(),owner:text('owner').notNull().unique(),receiverHash:text('receiver_hash').notNull(),senderHash:text('sender_hash').notNull(),offer:text('offer').notNull(),answer:text('answer'),expiresAt:integer('expires_at').notNull()});
export const musicListeners=sqliteTable('music_listeners',{scope:text('scope').primaryKey(),payload:text('payload').notNull(),updatedAt:integer('updated_at').notNull(),playId:text('play_id').notNull(),sequence:integer('sequence').notNull(),startedAt:integer('started_at').notNull().default(0),revision:text('revision').notNull().default('')});
export const musicPlays=sqliteTable('music_plays',{scope:text('scope').notNull(),playId:text('play_id').notNull(),startedAt:integer('started_at').notNull()},table=>[primaryKey({columns:[table.scope,table.playId]}),index('idx_music_plays_scope_started').on(table.scope,table.startedAt)]);
export const musicHistory=sqliteTable('music_history',{scope:text('scope').notNull(),trackKey:text('track_key').notNull(),payload:text('payload').notNull(),lastPlayedAt:integer('last_played_at').notNull()},table=>[primaryKey({columns:[table.scope,table.trackKey]}),index('idx_music_history_listener_time').on(table.scope,table.lastPlayedAt)]);
export const bookingRequests=sqliteTable('booking_requests',{id:text('id').primaryKey(),fingerprint:text('fingerprint').notNull(),date:text('date').notNull(),time:text('time').notNull(),name:text('name').notNull(),email:text('email').notNull(),notes:text('notes').notNull(),starts:integer('starts').notNull(),ends:integer('ends').notNull(),notification:text('notification').notNull().default('pending'),ipHash:text('ip_hash').notNull(),created:integer('created').notNull()},table=>[index('idx_booking_range').on(table.starts,table.ends),index('idx_booking_ip_created').on(table.ipHash,table.created)]);
export const quotaAccounts=sqliteTable('quota_accounts',{email:text('email').primaryKey(),name:text('name').notNull().default(''),hidden:integer('hidden').notNull().default(0),createdAt:text('created_at').notNull()});
export const quotaOfficialEvidence=sqliteTable('quota_official_evidence',{email:text('email').primaryKey(),payload:text('payload').notNull(),observedAt:text('observed_at').notNull()});
export const quotaOfficialHistory=sqliteTable('quota_official_history',{id:text('id').primaryKey(),email:text('email').notNull(),payload:text('payload').notNull(),observedAt:text('observed_at').notNull()},table=>[index('idx_quota_official_history_email_time').on(table.email,table.observedAt)]);
export const quotaQueryControl=sqliteTable('quota_query_control',{id:integer('id').primaryKey(),enabled:integer('enabled').notNull().default(1),intervalMinutes:integer('interval_minutes').notNull().default(5),workerSeenAt:integer('worker_seen_at').notNull().default(0),lastAttemptAt:integer('last_attempt_at').notNull().default(0)});
export const quotaQueries=sqliteTable('quota_queries',{id:text('id').primaryKey(),email:text('email'),state:text('state').notNull(),reason:text('reason').notNull(),requestedAt:integer('requested_at').notNull(),startedAt:integer('started_at'),finishedAt:integer('finished_at'),leaseToken:text('lease_token'),leaseUntil:integer('lease_until').notNull().default(0),verifiedEmail:text('verified_email'),resultCode:text('result_code'),fields:text('fields').notNull().default('[]')},table=>[index('idx_quota_queries_state_requested').on(table.state,table.requestedAt)]);
export const snapshots=sqliteTable("snapshots",{id:integer("id").primaryKey(),payload:text("payload").notNull(),updatedAt:text("updated_at").notNull()});
export const websites=sqliteTable("websites",{
 id:text("id").primaryKey(),url:text("url").notNull().unique(),title:text("title").notNull(),kind:text("kind").notNull(),source:text("source").notNull(),
 firstSeen:text("first_seen").notNull(),lastSeen:text("last_seen").notNull(),hidden:integer("hidden").notNull().default(0),customized:integer("customized").notNull().default(0),boxName:text("box_name").notNull().default("")
},table=>[index("idx_websites_visible_recent").on(table.hidden,table.lastSeen)]);
export const websiteEvents=sqliteTable("website_events",{id:text("id").primaryKey(),websiteId:text("website_id").notNull(),title:text("title").notNull(),observedAt:text("observed_at").notNull(),recordType:text("record_type").notNull().default("delivery")},table=>[index("idx_website_events_link_time").on(table.websiteId,table.observedAt)]);
export const websiteSync=sqliteTable("website_sync",{id:integer("id").primaryKey(),payload:text("payload").notNull()});
export const creditAccounts=sqliteTable("credit_accounts",{id:text("id").primaryKey(),label:text("label").notNull(),balance:text("balance"),unlimited:integer("unlimited").notNull().default(0),observedAt:text("observed_at").notNull()});
export const creditChanges=sqliteTable("credit_changes",{id:text("id").primaryKey(),accountId:text("account_id").notNull(),direction:text("direction").notNull(),amount:text("amount").notNull(),usdMicros:integer("usd_micros").notNull(),beforeBalance:text("before_balance").notNull(),afterBalance:text("after_balance").notNull(),observedAt:text("observed_at").notNull(),classification:text("classification").notNull()},table=>[index("idx_credit_changes_time").on(table.observedAt)]);
export const ledgerEntries=sqliteTable("ledger_entries",{id:text("id").primaryKey(),entryDate:text("entry_date").notNull(),currency:text("currency").notNull(),amount:text("amount").notNull(),usdMicros:integer("usd_micros").notNull(),rate:text("rate").notNull(),rateDate:text("rate_date").notNull(),note:text("note").notNull(),createdAt:text("created_at").notNull()});
export const ledgerSync=sqliteTable("ledger_sync",{id:integer("id").primaryKey(),payload:text("payload").notNull()});
export const mezipConnection=sqliteTable('mezip_connection',{id:integer('id').primaryKey(),deviceId:text('device_id').notNull(),online:integer('online').notNull(),lastSeen:integer('last_seen').notNull()});
export const localAppsRelay=sqliteTable('local_apps_relay',{id:integer('id').primaryKey(),deviceId:text('device_id').notNull(),relayUrl:text('relay_url').notNull(),lastSeen:integer('last_seen').notNull()});
export const mezipCommands=sqliteTable('mezip_commands',{id:text('id').primaryKey(),fingerprint:text('fingerprint').notNull(),deviceId:text('device_id').notNull(),method:text('method').notNull(),path:text('path').notNull(),body:text('body'),state:text('state').notNull(),createdAt:integer('created_at').notNull(),expires:integer('expires').notNull(),leaseUntil:integer('lease_until').notNull(),responseStatus:integer('response_status'),responseBody:text('response_body')},table=>[index('idx_mezip_commands_queue').on(table.deviceId,table.state,table.expires)]);
