// Shared only by the published atlas; original localhost map remains separate.
let pulseDeadline=performance.now()+8,pulsePaused=false,pulseLastFrame=0,pulseLabelsAt=0,pulseLastStatus=0,pulseCurrentStage='正在展开潮汕山海';
const pulseStageNames={buildTerrain:'展开山海地形',buildSurface:'连接河流与道路',traffic:'布置道路车辆',regionalLife:'布置街头生活',transport:'载入交通设施',cuisine:'载入地方美食',communityActivities:'载入社区活动',tourContext:'构建景点周边街区',regionalEnvironment:'载入自然环境',urbanEnvironment:'载入城市建筑',buildBuildings:'载入建筑',buildTrees:'载入山林',buildLandmarks:'载入各地景点',buildBorders:'载入地区边界',buildBoats:'载入船只',buildStars:'准备夜景',buildUI:'准备地图操作',spatialSurfaces:'整理地形',staticVisibility:'准备场景显示'};
function pulseStatus(state,label){pulseLastStatus=performance.now();if(state==='loading')pulseCurrentStage=label;if(window.parent!==window)window.parent.postMessage({type:'pulse-atlas-status',state,label},location.origin);}
function pulseNeedsYield(){return performance.now()>=pulseDeadline;}
async function pulseYield(){if(typeof window.scheduler?.yield==="function")await window.scheduler.yield();else await new Promise(resolve=>setTimeout(resolve,0));pulseDeadline=performance.now()+8;if(performance.now()-pulseLastStatus>1000)pulseStatus('loading',pulseCurrentStage);}
async function pulseStage(name,build){pulseStatus('loading',pulseStageNames[name]||'正在展开潮汕地图');const label=document.getElementById('loading-text');if(label)label.textContent=pulseStageNames[name]||'正在展开潮汕地图';await pulseYield();const started=performance.now();const value=await build();Jd[name]=Math.round(performance.now()-started);await pulseYield();return value;}
const pulseTrackOrders=new WeakMap();
function pulseTrackOrder(tracks){if(pulseTrackOrders.has(tracks))return pulseTrackOrders.get(tracks);const ordered=tracks.slice();let seed=617;for(let i=ordered.length-1;i>0;i--){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const j=seed%(i+1);[ordered[i],ordered[j]]=[ordered[j],ordered[i]];}pulseTrackOrders.set(tracks,ordered);return ordered;}
function pulseUpdateLabels(now){if(now-pulseLabelsAt<100)return;pulseLabelsAt=now;Qy();}
window.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==window.parent||event.data?.type!=='pulse-atlas-visibility')return;pulsePaused=event.data.visible===false;});

const pulseDetailGates=[];
function pulsePrepareRender(){for(const gate of pulseDetailGates)gate.visible=ki/Kt.zoom<10;const near=ki/Kt.zoom<8;qe.castShadow=near;ln.shadowMap.autoUpdate=near;}

function pulseDrawGroups(scene,camera){const frustum=new vo().setFromProjectionMatrix(new ce().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse));return scene.children.map(root=>{let calls=0,triangles=0,samples=[];root.traverseVisible(o=>{if(!o.isMesh||o.frustumCulled&&!frustum.intersectsObject(o))return;calls++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position?.count||0)/3*(o.isInstancedMesh?o.count:1);if(samples.length<3)samples.push(o.name||o.parent?.name||o.type)});return {name:root.name,type:root.type,id:root.id,calls,triangles,samples}}).filter(x=>x.calls).sort((a,b)=>b.calls-a.calls)}

async function pulseCompactSurfaces(scene){const pending=[];scene.updateMatrixWorld(true);scene.traverse(lod=>{if(!lod.isLOD||lod.levels.length!==2)return;const near=lod.levels[0].object,far=lod.levels[1].object;if(!near.userData.staticSpatialTiles||!far.isMesh||far.isInstancedMesh)return;far.geometry.computeBoundingBox();far.updateWorldMatrix(true,false);const box=far.geometry.boundingBox.clone().applyMatrix4(far.matrixWorld),size=box.getSize(new $);if(Math.max(size.x,size.z)<=6)pending.push({lod,near,far});});for(const{lod,near,far}of pending){lod.removeLevel(0);lod.levels[0].distance=0;far.visible=true;lod._currentLevel=0;near.traverse(mesh=>{if(mesh.isMesh)mesh.geometry.dispose()});if(pulseNeedsYield())await pulseYield();}return pending.length;}

function pulseInstallDetailLOD(scene){const names=new Set(['tour-street-fabric','aviation-and-rail','regional-cuisine','regional-people','community-recreation']);for(const root of [...scene.children]){if(!names.has(root.name))continue;const gate=new bt;gate.name='distance-detail:'+root.name;scene.add(gate);gate.add(root);const update=gate.updateMatrixWorld;gate.updateMatrixWorld=function(force){if(this.visible)update.call(this,force)};pulseDetailGates.push(gate);}}
