import {mountCommunityMap} from './opc-community-map.mjs';
import {loadContent, esc, safeUrl, communityCard, policyCard, activityCard} from './opc-content.mjs';

import './opc-hub.css';

const KEY='chaoshan-opc-atlas:v1';
const icons={pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z M9 10a3 3 0 1 0 6 0a3 3 0 1 0-6 0',search:'m21 21-5-5 M18 10a8 8 0 1 1-16 0a8 8 0 1 1 16 0',arrow:'M5 12h14m-6-6 6 6-6 6',plus:'M12 5v14M5 12h14',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8',map:'m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3ZM9 3v15M15 6v15',close:'m6 6 12 12M6 18 18 6',chevron:'m9 5 7 7-7 7',external:'M14 3h7v7m0-7L10 14M10 3H3v18h18v-7'};
const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${(icons[name]||icons.pin).split(' M').map((d,i)=>`<path d="${i?'M':''}${d}"/>`).join('')}</svg>`;
let data={communities:[],policies:[],activities:[],meta:{}},state={tab:'communities',q:'',city:'全部城市',board:'red',kind:'all',page:1,collection:'places'};
let communityMap=null,selectedMapId=null;
let storageError=false,saved={favorites:[],places:[]};
try{const v=JSON.parse(localStorage.getItem(KEY)||'null');if(v&&Array.isArray(v.favorites)&&Array.isArray(v.places)){saved={favorites:v.favorites.filter(x=>typeof x==='string'),places:v.places.filter(p=>p&&typeof p.id==='string'&&typeof p.name==='string'&&Number.isFinite(p.lng)&&Number.isFinite(p.lat))};}}catch{storageError=true;}
const hub=document.createElement('section');hub.id='opc-hub';hub.setAttribute('aria-label','潮汕社区探索');
hub.innerHTML=`<header class="opc-header"><button class="opc-brand" data-tab="communities" aria-label="社区探索首页"><span class="opc-brand-mark">${icon('map')}</span><span><strong>潮汕 <i>共创地图</i></strong><small>CHAOSHAN · COMMUNITY ATLAS</small></span></button><nav aria-label="社区导航"><button data-tab="communities">社区发现</button><button data-tab="rankings">社区榜单</button><button data-tab="activities">活动与政策</button><button data-tab="saved">我的地点<span id="opc-saved-count"></span></button></nav><button class="opc-map-link" data-map>${icon('map')}<span>进入 3D 地图</span>${icon('arrow')}</button></header><div id="opc-scroll"><main id="opc-main"><div class="opc-loading"><span></span>正在整理社区与城市的连接…</div></main><footer class="opc-footer"><span>沿着江河，走向山海。也走向一起创造的人。</span><span><a href="/local-apps/chaoshan-atlas/index.html#map" target="_blank" rel="noopener">独立打开潮汕 3D 地图 ↗</a><a href="https://betteropc.com/opc-activities" target="_blank" rel="noopener noreferrer">内容来源 BetterOPC ↗</a></span></footer></div>`;
document.body.append(hub);document.body.classList.add('opc-hub-open');
const dock=document.createElement('button');dock.className='opc-map-dock';dock.dataset.mapObstacle='';dock.innerHTML=`${icon('map')}<span>社区 · 活动 · 地点</span><b>探索 ${icon('arrow')}</b>`;dock.onclick=()=>showHub();document.body.append(dock);
function alignMapDock(){const actions=document.querySelector('.top-actions');dock.style.top=innerWidth<=1100&&actions?`${Math.max(130,actions.getBoundingClientRect().bottom+12)}px`:'';}
new ResizeObserver(alignMapDock).observe(document.querySelector('.top-actions'));window.addEventListener('resize',alignMapDock);alignMapDock();
const detail=document.createElement('dialog');detail.className='opc-dialog';detail.setAttribute('aria-label','详细信息');document.body.append(detail);
const editor=document.createElement('dialog');editor.className='opc-dialog opc-editor';editor.setAttribute('aria-label','新增地点');document.body.append(editor);
const notice=document.createElement('div');notice.className='opc-notice';notice.setAttribute('role','status');notice.hidden=true;document.body.append(notice);
let noticeTimer;function notify(msg){notice.textContent=msg;notice.hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>notice.hidden=true,4200);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));storageError=false;return true;}catch{notify('浏览器未能保存，请导出地点备份后再试。');return false;}}
let mapPromise=null,pendingPlace=null;
function ensureMap(){if(!mapPromise)mapPromise=window.loadCommunityAtlas().catch(()=>{mapPromise=null;showHub();notify('地图模块未能载入，请稍后重试。');});return mapPromise;}
function syncPins(){window.chaoshanAtlas?.setCustomPlaces(saved.places);}
window.addEventListener('atlas:ready',()=>{syncPins();if(pendingPlace){const p=pendingPlace;pendingPlace=null;const result=window.chaoshanAtlas.focusCoordinates(p);notify(result.ok?`已定位：${p.name}`:result.reason);}});
window.addEventListener('opc:open-place',e=>openPlace(e.detail.id));
window.addEventListener('storage',e=>{if(e.key===KEY){try{const value=JSON.parse(e.newValue);if(value&&Array.isArray(value.favorites)&&Array.isArray(value.places)){saved=value;syncPins();render();}}catch{}}});
function showHub(tab=state.tab){hub.hidden=false;document.body.classList.add('opc-hub-open');history.replaceState(null,'','#communities');state.tab=tab;render();}
function showMap(){ensureMap();hub.hidden=true;document.body.classList.remove('opc-hub-open');history.replaceState(null,'','#map');document.querySelector('#viewport')?.focus({preventScroll:true});}
function locatePlace(p){if(!p)return;if(!window.chaoshanAtlas){pendingPlace=p;detail.close();showMap();notify('正在展开 3D 地图，加载完成后会自动定位。');return;}const result=window.chaoshanAtlas.focusCoordinates(p);if(!result.ok){notify(result.reason);return;}detail.close();showMap();notify(`已定位：${p.name}`);}
const cities=()=>[...new Set((state.tab==='activities'?data.policies:data.communities).map(p=>p.city).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-CN'));
const filters=(placeholder)=>`<div class="opc-filterbar"><div class="opc-section-label"><span class="opc-dot"></span>${state.tab==='activities'?'把机会带到身边':'找到适合你的社区'}</div><div class="opc-filter-inputs"><label class="opc-search">${icon('search')}<input id="opc-search" type="search" maxlength="100" placeholder="${placeholder}" value="${esc(state.q)}" aria-label="搜索社区或政策"></label><label class="opc-city-label">${icon('pin')}<select id="opc-city" aria-label="筛选城市"><option>全部城市</option>${cities().map(c=>`<option ${state.city===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div></div>`;
function intro(kicker,title,desc,button=''){return `<section class="opc-page-intro"><div><div class="opc-kicker">${kicker}</div><h1>${title}</h1><p>${desc}</p></div>${button}</section>`;}
function stats(){return `<div class="opc-stats"><div><b>${data.communities.length}<i> 个</i></b><span>社区探索</span></div><div><b>${new Set(data.communities.map(c=>c.city)).size}<i> 座</i></b><span>连接城市</span></div><div><b>${data.policies.length}<i> 条</i></b><span>城市政策</span></div><div class="opc-stat-note"><span class="opc-dot"></span><span>公开内容快照 · ${esc(data.meta.snapshotDate||'2026-09-26')}<small>社区信息、榜单与图片来自 BetterOPC</small></span></div></div>`;}
function empty(title='没有找到匹配内容',desc='试试其他关键词，或切换到全部城市。'){return `<div class="opc-empty">${icon('search')}<h3>${title}</h3><p>${desc}</p>${state.q||state.city!=='全部城市'?'<button class="opc-button" data-reset>清除筛选</button>':''}</div>`;}
function matches(p){return (state.city==='全部城市'||p.city===state.city)&&(!state.q||[p.name,p.title,p.summary,p.city,p.district,...(p.tags||[])].join(' ').toLowerCase().includes(state.q.trim().toLowerCase()));}
function mapSection(){return `<section class="opc-community-map-section" id="opc-community-map-section" aria-label="全国社区地图"><div class="opc-community-map-heading"><div><span class="opc-kicker">COMMUNITY MAP · 全国社区分布</span><h2>在地图上，找到同路人。</h2></div><div class="opc-map-switch"><span class="active">全国社区</span><button data-map>${icon('map')} 潮汕 3D</button><button data-map-expand aria-expanded="false" aria-label="展开全国社区地图">⤢</button></div></div><div class="opc-community-map-layout"><div class="opc-map-canvas-wrap"><div id="opc-community-map" role="region" aria-label="可缩放拖动的全国社区地图"></div><button class="opc-map-fit" data-map-fit>${icon('pin')} 全部结果</button></div><aside id="opc-map-preview" class="opc-map-preview" aria-live="polite"></aside></div><div class="opc-community-map-foot"><span><i class="opc-map-dot-green"></i> 推荐关注 <i class="opc-map-dot-orange"></i> 入驻前留意</span><span id="opc-map-count"></span></div></section>`;}
function updateMapPreview(items=data.communities.filter(matches)){const target=document.querySelector('#opc-map-preview');if(!target)return;const selected=items.find(p=>p.id===selectedMapId)||items.find(p=>p.board==='red')||items[0];selectedMapId=selected?.id||null;target.innerHTML=selected?`<div class="opc-map-preview-label">地图中的社区 <span>点击标记切换</span></div>${communityCard(selected,{saved:saved.favorites.includes(selected.id)})}`:`<div class="opc-empty"><h3>这个范围暂无社区</h3><p>试试其他城市或关键词。</p></div>`;const valid=items.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng));document.querySelector('#opc-map-count').textContent=`${valid.length} 个概览坐标 · 来源坐标系未声明`;}
function mountMap(){const host=document.querySelector('#opc-community-map');if(!host)return;const items=data.communities.filter(matches);communityMap=mountCommunityMap(host,{communities:items,onSelect:id=>{selectedMapId=id;updateMapPreview();}});updateMapPreview(items);}
function expandCommunityMap(force){const section=document.querySelector('#opc-community-map-section');if(!section)return;const expanded=force??!section.classList.contains('opc-map-expanded');section.classList.toggle('opc-map-expanded',expanded);const button=section.querySelector('[data-map-expand]');button.setAttribute('aria-expanded',String(expanded));button.setAttribute('aria-label',expanded?'收起全国社区地图':'展开全国社区地图');button.textContent=expanded?'×':'⤢';requestAnimationFrame(()=>communityMap?.invalidate());}
function showCommunityMap(id){if(detail.open)detail.close();selectedMapId=id||selectedMapId;state.q='';state.city='全部城市';showHub('communities');history.replaceState(null,'','#community-map');document.querySelector('#opc-community-map-section')?.scrollIntoView({behavior:'instant',block:'start'});if(id){communityMap?.focus(id);updateMapPreview();}}
document.addEventListener('click',event=>{const button=event.target.closest('[data-community-map]');if(button)showCommunityMap(button.dataset.communityMap||null);});
if(import.meta.env.DEV)window.opcCommunityMapState=()=>communityMap?.getState()||null;
function communityResults(){const items=data.communities.filter(matches);return `<div class="opc-results-heading"><h2>发现社区 <span>${items.length}</span></h2><span>全国精选 · 以公开信息为准</span></div><div class="opc-grid">${items.map(p=>communityCard(p,{saved:saved.favorites.includes(p.id)})).join('')}</div>${items.length?'':empty()}`;}
function communityView(){const hero=data.communities.find(c=>c.board==='red'&&c.image)||data.communities[0];return `<section class="opc-hero"><div class="opc-hero-copy"><div class="opc-kicker"><span class="opc-dot"></span> 从山海出发，与同路人相遇</div><h1>一个人的事业，<br>一群人的<span>可能。</span></h1><p>找到一处有温度的空间，连接一群志同道合的人。<br>从潮汕到更多城市，让想法在真实的地方生长。</p><div class="opc-hero-actions"><button class="opc-button opc-primary" data-discover>发现理想社区 ${icon('arrow')}</button><button class="opc-text-button" data-add>${icon('plus')} 记录我的地点</button></div><div class="opc-hero-foot"><span class="opc-small-emblem">山</span><span>有地方可去，有伙伴同行。</span></div></div><button class="opc-hero-photo" data-community="${esc(hero?.id||'')}"><img src="${esc(safeUrl(hero?.image)||'')}" alt="${esc(hero?.name||'社区空间')}" fetchpriority="high"><span class="opc-image-shade"></span><span class="opc-photo-label">COMMUNITY SPOTLIGHT <b>值得被发现的共创空间</b></span><span class="opc-photo-caption"><span>${icon('pin')} ${esc(hero?.city||'')} · ${esc(hero?.name||'')}</span><i>${icon('arrow')}</i></span></button></section>${stats()}<section id="opc-discovery">${filters('搜索社区、城市或资源…')}${mapSection()}<div id="opc-results">${communityResults()}</div></section>`;}
function rankResults(){const items=data.communities.filter(p=>p.board===state.board).filter(matches);return `<div class="opc-rank-note">${state.board==='red'?'值得关注的社区线索，进一步了解运营与入驻条件。':'入驻前留意：下列内容是来源平台的评价观点，请结合原始资料与实地了解作判断。'}</div><div class="opc-grid opc-ranking-grid">${items.map((p,i)=>communityCard(p,{saved:saved.favorites.includes(p.id),rank:p.sourceRank||i+1})).join('')}</div>${items.length?'':empty()}`;}
function rankingView(){return `${intro('COMMUNITY SIGNALS · 社区观察','找到你的下一站。','借一份社区榜单，认识不同空间的资源、运营与入驻条件。')}<div class="opc-segment" role="group" aria-label="榜单类别"><button data-board="red" class="${state.board==='red'?'active':''}">推荐关注 <span>${data.communities.filter(p=>p.board==='red').length}</span></button><button data-board="black" class="${state.board==='black'?'active':''}">入驻前留意 <span>${data.communities.filter(p=>p.board==='black').length}</span></button><small>来源榜单快照 · 非本站评分</small></div>${filters('搜索榜单社区…')}<div id="opc-results">${rankResults()}</div>`;}
function opportunityResults(){const policies=data.policies.filter(matches);const activities=data.activities.filter(p=>matches(p)||(p.city==='全国'&&(!state.q||[p.title,p.summary,...(p.tags||[])].join(' ').toLowerCase().includes(state.q.trim().toLowerCase()))));const pageItems=policies.slice(0,state.page*12);return `${state.kind!=='policies'?`<div class="opc-results-heading"><h2>平台活动 <span>${activities.length}</span></h2><span>申请条件以官方页面为准</span></div><div class="opc-activity-grid">${activities.map(activityCard).join('')}</div>${activities.length?'':empty('当前城市暂无平台活动','切换到全部城市，查看平台活动。')}`:''}${state.kind!=='activities'?`<div class="opc-results-heading opc-policy-heading"><h2>城市政策 <span>${policies.length}</span></h2><span>政策线索 · 可追溯来源</span></div><div class="opc-policy-grid">${pageItems.map(policyCard).join('')}</div>${policies.length?'':empty()}${pageItems.length<policies.length?`<button class="opc-load-more" data-more>继续浏览 <span>已显示 ${pageItems.length} / ${policies.length}</span> ${icon('plus')}</button>`:''}`:''}`;}
function activitiesView(){return `${intro('OPPORTUNITIES · 在城市里，找到机会','让每一步，都有支持。','整理城市创业政策与平台扶持活动，让空间之外的资源也触手可及。')}<div class="opc-opportunity-banner"><div>${icon('pin')}<b>${new Set(data.policies.map(p=>p.city)).size} 座城市的支持线索</b><span>补贴支持 / 创业服务 / 算力资源 / 空间入驻</span></div><small>采集于 ${esc(data.meta.snapshotDate)} · 具体有效期与资格请查看来源</small></div><div class="opc-segment" aria-label="机会类型"><button data-kind="all" class="${state.kind==='all'?'active':''}">全部机会</button><button data-kind="policies" class="${state.kind==='policies'?'active':''}">城市政策</button><button data-kind="activities" class="${state.kind==='activities'?'active':''}">平台活动</button></div>${filters('搜索政策、资源或关键词…')}<div id="opc-results">${opportunityResults()}</div>`;}
function placeCard(p){return `<article class="opc-place-card"><div class="opc-place-symbol">${icon('pin')}</div><div><span class="opc-eyebrow">${esc(p.city||'我的地点')} · ${esc(p.category||'自定义')}</span><h3>${esc(p.name)}</h3><p>${esc(p.address||p.notes||'留给下一次出发的坐标')}</p><small>${p.lng.toFixed(5)}° E · ${p.lat.toFixed(5)}° N</small></div><button class="opc-icon-button" data-place="${esc(p.id)}" aria-label="查看${esc(p.name)}详情">${icon('arrow')}</button></article>`;}
function savedView(){const favorites=data.communities.filter(p=>saved.favorites.includes(p.id));return `${intro('YOUR PLACES · 给下一次出发留个坐标','我的地点，我的连接。','收藏喜欢的社区，记录自己的空间。所有记录保存在当前浏览器的新站中。',`<button class="opc-button opc-primary" data-add>${icon('plus')} 新增地点</button>`)}<div class="opc-segment"><button data-collection="places" class="${state.collection==='places'?'active':''}">我的地点 <span>${saved.places.length}</span></button><button data-collection="favorites" class="${state.collection==='favorites'?'active':''}">收藏社区 <span>${favorites.length}</span></button><button class="opc-export" data-export>${icon('external')} 导出地点备份</button></div>${storageError?'<p class="opc-rank-note">本次未能读取已有浏览器记录；可先导出当前记录备份。</p>':''}${state.collection==='places'?`<div class="opc-place-hint">${icon('map')}潮汕范围内的坐标可直接在 3D 地图定位，全国其他地点可打开外部地图。</div><div class="opc-places-grid">${saved.places.map(placeCard).join('')}</div>${saved.places.length?'':`<div class="opc-empty">${icon('pin')}<h3>为喜欢的地方，留下一个坐标。</h3><p>办公室、咖啡馆、共创空间，或者你的下一个目的地。</p><button class="opc-button opc-primary" data-add>${icon('plus')} 添加第一个地点</button></div>`}`:`<div class="opc-grid">${favorites.map(p=>communityCard(p,{saved:true})).join('')}</div>${favorites.length?'':empty('还没有收藏社区','在社区卡片上点击收藏，就能在这里再次找到它。')}`}`;}
function updateResults(){const target=document.querySelector('#opc-results');if(target)target.innerHTML=state.tab==='communities'?communityResults():state.tab==='rankings'?rankResults():opportunityResults();if(communityMap){const items=data.communities.filter(matches);communityMap.setItems(items);updateMapPreview(items);}}
function render(){communityMap?.destroy();communityMap=null;document.querySelector('#opc-main').innerHTML=state.tab==='communities'?communityView():state.tab==='rankings'?rankingView():state.tab==='activities'?activitiesView():savedView();document.querySelectorAll('.opc-header [data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===state.tab);if(b.dataset.tab===state.tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});document.querySelector('#opc-saved-count').textContent=saved.places.length+saved.favorites.length||'';mountMap();}
const external=(url,label,cls='opc-button')=>safeUrl(url)?`<a class="${cls}" href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${label} ${icon('external')}</a>`:'';
const mapUrl=p=>`https://map.baidu.com/search/${encodeURIComponent([p.city,p.address||p.name].filter(Boolean).join(' '))}`;
function dialogHead(kicker,title){return `<div class="opc-dialog-header"><span class="opc-kicker">${kicker}</span><button class="opc-icon-button" data-close aria-label="关闭详情">${icon('close')}</button></div><h2>${esc(title)}</h2>`;}
function displayDetail(html){detail.innerHTML=html;if(!detail.open)detail.showModal();detail.scrollTop=0;}
function openCommunity(id){const p=data.communities.find(c=>c.id===id);if(!p)return;displayDetail(`${dialogHead('COMMUNITY PROFILE · 社区档案',p.name)}<div class="opc-detail-meta">${icon('pin')}${esc(p.city)} · ${esc(p.district||'')}<span>${p.board==='red'?'来源榜单 · 推荐关注':'来源榜单 · 入驻前留意'}</span></div><img class="opc-detail-image" src="${esc(safeUrl(p.image)||'')}" alt="${esc(p.name)}社区图片"><div class="opc-detail-columns"><div><h3>空间与资源</h3><p>${esc(p.summary||'公开页面暂无详细介绍')}</p><div class="opc-detail-tags">${(p.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div><h3>入驻条件</h3><p>${esc(p.admission||'请联系运营方核实入驻条件。')}</p><h3>费用与支持</h3><p>${esc(p.fee||'来源未公开具体费用，请与运营方确认。')}</p></div><aside><span class="opc-eyebrow">社区信息</span><dl><dt>运营机构</dt><dd>${esc(p.operator||'暂无公开信息')}</dd><dt>地址</dt><dd>${esc(p.address||[p.city,p.district].filter(Boolean).join(' · '))}</dd><dt>榜单说明</dt><dd>${esc(p.reason||'来源平台收录')}</dd></dl><button class="opc-button" data-save="${esc(p.id)}">${icon('heart')}${saved.favorites.includes(id)?'已收藏 · 点击取消':'收藏这个社区'}</button><button class="opc-button" data-community-map="${esc(p.id)}">${icon('pin')} 在社区地图定位</button>${external(mapUrl(p),'外部地图')}</aside></div><div class="opc-source-note">公开内容快照 · ${esc(data.meta.snapshotDate)}。榜单内容为 BetterOPC 的评价观点；原始坐标系未声明，地图通过名称与地址检索。</div><div class="opc-dialog-actions">${external(p.referenceUrl||p.sourceUrl,'查看社区来源','opc-button opc-primary')}${p.sourceUrl&&p.sourceUrl!==p.referenceUrl?external(p.sourceUrl,'相关资料'):''}</div>`);}
function openPolicy(id){const p=data.policies.find(p=>p.id===id);if(!p)return;displayDetail(`${dialogHead('CITY POLICY · 城市政策',p.title)}<div class="opc-detail-meta">${icon('pin')}${esc(p.city)}<span>${esc(p.categoryLabel||'城市支持')}</span></div><p class="opc-detail-lead">${esc(p.summary||'查看来源页面了解政策详情及申请要求。')}</p><div class="opc-policy-facts"><div><span>来源</span><b>${esc(p.sourceName||'BetterOPC')}</b></div><div><span>发布日期</span><b>${esc(p.date||'来源未注明')}</b></div></div><div class="opc-source-note">此处展示公开政策摘录。申报资格、截止日期、申请材料与兑现方式，请以官方最新发布为准。采集日期：${esc(data.meta.snapshotDate)}。</div><div class="opc-dialog-actions">${external(p.url,'查看来源摘录','opc-button opc-primary')}</div>`);}
function openActivity(id){const p=data.activities.find(p=>p.id===id);if(!p)return;displayDetail(`${dialogHead('PLATFORM OPPORTUNITY · 平台活动',p.title)}${p.image?`<img class="opc-detail-image" src="${esc(safeUrl(p.image))}" alt="${esc(p.title)}">`:''}<p class="opc-detail-lead">${esc(p.summary||'')}</p><div class="opc-policy-facts"><div><span>活动时间</span><b>${esc(p.date||'请查看官方活动页面')}</b></div><div><span>适用地区</span><b>${esc(p.city||'全国')}</b></div></div>${p.eligibility?`<h3>参与条件</h3><p>${esc(p.eligibility)}</p>`:''}<div class="opc-source-note">活动信息为 ${esc(data.meta.snapshotDate)} 的公开快照。申请将在活动官方页面进行，名额、时间和权益以主办方说明为准。</div><div class="opc-dialog-actions">${external(p.url,'前往官方活动','opc-button opc-primary')}</div>`);}
function openPlace(id){const p=saved.places.find(p=>p.id===id);if(!p)return;displayDetail(`${dialogHead('YOUR PLACE · 我的地点',p.name)}<div class="opc-detail-meta">${icon('pin')}${esc(p.city)} · ${esc(p.category)}</div>${p.image?`<img class="opc-detail-image" src="${esc(safeUrl(p.image))}" alt="${esc(p.name)}">`:''}<p>${esc(p.address||'未填写详细地址')}</p><p class="opc-detail-lead">${esc(p.notes||'还没有地点笔记。')}</p><div class="opc-source-note">经纬度：${p.lng.toFixed(6)}，${p.lat.toFixed(6)} · 由你在本机记录</div><div class="opc-dialog-actions"><button class="opc-button opc-primary" data-locate="${esc(id)}">${icon('map')} 在 3D 地图定位</button>${external(mapUrl(p),'外部地图')}<button class="opc-button" data-edit="${esc(id)}">编辑地点</button><button class="opc-text-button opc-danger" data-delete="${esc(id)}">移除地点</button></div>`);}
function openEditor(id){const p=saved.places.find(p=>p.id===id)||{};editor.innerHTML=`${dialogHead('PIN A POSSIBILITY · 记录一个新可能',p.id?'编辑地点':'新增我的地点')}<p class="opc-editor-intro">给这个地点一个名字。潮汕范围内的坐标会同步为 3D 地图标记。</p><form id="opc-place-form"><input type="hidden" name="id" value="${esc(p.id||'')}"><div class="opc-form-grid"><label>地点名称 <b>*</b><input name="name" required maxlength="80" value="${esc(p.name||'')}" placeholder="例如：我的共创空间"></label><label>所在城市 <b>*</b><input name="city" required maxlength="30" value="${esc(p.city||'汕头')}" placeholder="例如：汕头"></label><label class="opc-full">详细地址<input name="address" maxlength="200" value="${esc(p.address||'')}" placeholder="街道、门牌或附近地标"></label><label>经度 <b>*</b><input name="lng" type="number" min="-180" max="180" step="any" required value="${p.lng??116.6822}" aria-describedby="opc-coordinate-help"></label><label>纬度 <b>*</b><input name="lat" type="number" min="-90" max="90" step="any" required value="${p.lat??23.3535}" aria-describedby="opc-coordinate-help"></label><p class="opc-form-hint opc-full" id="opc-coordinate-help">填写十进制 WGS84 坐标。默认坐标仅是汕头参考点，请按实际地点调整。全国地点均可保存；超出潮汕范围的地点使用外部地图查看。</p><label>地点类型<select name="category">${['共创空间','办公空间','咖啡馆','活动场地','文化空间','其他'].map(v=>`<option ${v===p.category?'selected':''}>${v}</option>`).join('')}</select></label><label>图片链接（选填）<input name="image" type="url" maxlength="2000" value="${esc(p.image||'')}" placeholder="https://…"></label><label class="opc-full">地点笔记<textarea name="notes" rows="3" maxlength="1000" placeholder="为什么喜欢这里？有什么值得记录？">${esc(p.notes||'')}</textarea></label></div><p class="opc-form-error" id="opc-form-error" role="alert"></p><div class="opc-dialog-actions"><button class="opc-button opc-primary" type="submit">${icon('pin')} 保存地点</button><button class="opc-button" type="button" data-close>取消</button><small>仅保存到当前浏览器</small></div></form>`;if(!editor.open)editor.showModal();editor.querySelector('[name=name]').focus();}
editor.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target),p=Object.fromEntries(fd);p.name=p.name.trim();p.city=p.city.trim();p.lng=Number(p.lng);p.lat=Number(p.lat);if(!p.name||!p.city||!Number.isFinite(p.lng)||!Number.isFinite(p.lat)||Math.abs(p.lng)>180||Math.abs(p.lat)>90){editor.querySelector('#opc-form-error').textContent='请填写地点名称、城市与有效的经纬度。';return;}if(p.image&&!safeUrl(p.image)){editor.querySelector('#opc-form-error').textContent='图片链接需要以 https:// 或 http:// 开头。';return;}p.id=p.id||'local-'+crypto.randomUUID();const previous=[...saved.places];const index=saved.places.findIndex(x=>x.id===p.id);if(index<0)saved.places.push(p);else saved.places[index]=p;if(!persist()){saved.places=previous;return;}syncPins();editor.close();if(detail.open)detail.close();state.collection='places';state.q='';state.city='全部城市';showHub('saved');notify('地点已保存，可以在详情中定位或继续编辑。');});
function toggleSave(id){const previous=[...saved.favorites];if(saved.favorites.includes(id))saved.favorites=saved.favorites.filter(x=>x!==id);else saved.favorites.push(id);if(!persist()){saved.favorites=previous;return;}render();if(detail.open)openCommunity(id);notify(saved.favorites.includes(id)?'已加入收藏社区':'已取消收藏');}
let deletedPlace=null;
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.hasAttribute('data-tab')){state={...state,tab:b.dataset.tab,q:'',city:'全部城市',page:1};render();document.querySelector('#opc-scroll').scrollTop=0;}else if(b.hasAttribute('data-map'))showMap();else if(b.hasAttribute('data-map-fit'))communityMap?.fit();else if(b.hasAttribute('data-map-expand'))expandCommunityMap();else if(b.hasAttribute('data-discover'))document.querySelector('#opc-discovery')?.scrollIntoView({behavior:'smooth'});else if(b.hasAttribute('data-add'))openEditor();else if(b.dataset.community)openCommunity(b.dataset.community);else if(b.dataset.policy)openPolicy(b.dataset.policy);else if(b.dataset.activity)openActivity(b.dataset.activity);else if(b.dataset.place)openPlace(b.dataset.place);else if(b.dataset.save)toggleSave(b.dataset.save);else if(b.dataset.board){state.board=b.dataset.board;render();}else if(b.dataset.kind){state.kind=b.dataset.kind;state.page=1;render();}else if(b.dataset.collection){state.collection=b.dataset.collection;render();}else if(b.hasAttribute('data-more')){state.page++;updateResults();}else if(b.hasAttribute('data-reset')){state.q='';state.city='全部城市';render();}else if(b.hasAttribute('data-close'))b.closest('dialog')?.close();else if(b.dataset.edit)openEditor(b.dataset.edit);else if(b.dataset.locate){const p=saved.places.find(p=>p.id===b.dataset.locate);locatePlace(p);}else if(b.dataset.delete){deletedPlace=saved.places.find(p=>p.id===b.dataset.delete);const previous=[...saved.places];saved.places=saved.places.filter(p=>p.id!==b.dataset.delete);if(!persist()){saved.places=previous;return;}syncPins();detail.close();showHub('saved');notice.innerHTML='地点已移除。 <button data-undo>撤销</button>';notice.hidden=false;clearTimeout(noticeTimer);}else if(b.hasAttribute('data-undo')&&deletedPlace){saved.places.push(deletedPlace);if(persist()){deletedPlace=null;syncPins();render();notify('地点已恢复');}}else if(b.hasAttribute('data-export')){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),...saved},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='潮汕共创地图-我的地点.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('地点与收藏备份已导出。');}});
hub.addEventListener('input',e=>{if(e.target.id==='opc-search'){state.q=e.target.value;state.page=1;updateResults();}});hub.addEventListener('change',e=>{if(e.target.id==='opc-city'){state.city=e.target.value;state.page=1;updateResults();}});
document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement&&e.target.closest('#opc-hub,.opc-dialog')){e.target.classList.add('opc-image-unavailable');e.target.alt='暂时无法显示图片 · 可查看来源';} },true);
for(const d of [detail,editor])d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
loadContent().then(value=>{data=value;render();syncPins();window.parent.postMessage({type:'pulse-community-status',state:'ready'},location.origin);if(location.hash==='#map')showMap();else showCommunityMap();}).catch(()=>{window.parent.postMessage({type:'pulse-community-status',state:'ready'},location.origin);document.querySelector('#opc-main').innerHTML='<div class="opc-empty"><h1>社区资料暂时未能加载</h1><p>请刷新页面重试，或先进入 3D 地图探索。</p><button class="opc-button opc-primary" data-map>进入 3D 地图</button></div>';});




window.addEventListener('hashchange',()=>{if(location.hash==='#map')showMap();else if(location.hash==='#community-map')showCommunityMap();else if(hub.hidden)showHub();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('.opc-map-expanded'))expandCommunityMap(false);});
