import assert from 'node:assert/strict';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {readFile,readdir,writeFile} from 'node:fs/promises';
import {scryptSync} from 'node:crypto';
import path from 'node:path';
const checks=[],PASSWORD='Cloud isolated smoke password!',salt='c0'.repeat(16),migrationToken='cloud-isolated-migration-token';
const initialHash=salt+':'+scryptSync(PASSWORD,Buffer.from(salt,'hex'),64,{N:32768,r:8,p:1,maxmem:64*1024*1024}).toString('hex');
let mf,worker,cookie='';
async function request(route,{method='GET',data,form,auth=true,headers={}}={}){
 const init={method,headers:{...(auth&&cookie?{Cookie:cookie}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},...(form?{body:form}:data?{body:JSON.stringify(data)}:{})};
 // Node's native FormData is not the bridge's FormData class. Serialize it
 // through a native Request so the real multipart body and boundary survive.
 if(form){const serialized=new Request('https://bookshelf.test'+route,init);init.headers=Object.fromEntries(serialized.headers);init.body=await serialized.arrayBuffer()}
 const response=await worker.fetch('https://bookshelf.test'+route,init);const type=response.headers.get('content-type')||'';const body=type.includes('json')?await response.json():await response.text();return {response,data:body}
}
async function check(name,fn){await fn();checks.push(name);console.log('PASS',name)}
const link={url:'https://www.gutenberg.org/ebooks/1342.epub3.images',label:'下载 EPUB',source:'Project Gutenberg',kind:'download',format:'EPUB',title:'Pride and Prejudice',author:'Jane Austen',language:'en'};
try{
 const options=convertV4MiniflareOptions({workers:[{
  name:'bookshelf',modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2026-09-30',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],
  bindings:{INITIAL_PASSWORD_HASH:initialHash,MIGRATION_TOKEN:migrationToken},
  assets:{directory:'dist/client',binding:'ASSETS',run_worker_first:true,assetConfig:{not_found_handling:'single-page-application'}}
 }]});
 mf=new Miniflare(options);
 worker=await mf.getWorker('bookshelf');
 const db=await mf.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql'))){const sql=await readFile(path.join('drizzle',file),'utf8');for(const statement of sql.split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(statement).run()}
 await check('actual workerd starts with migrated password hash and 66 books',async()=>{const auth=await request('/api/auth/status');assert.deepEqual(auth.data,{configured:true,authenticated:false});assert.equal((await request('/api/library')).data.books.length,66)});
 await check('private book mutations and ebook queries reject anonymous requests',async()=>{assert.equal((await request('/api/books',{method:'POST',data:{title:'No'}})).response.status,401);assert.equal((await request('/api/ebooks?title=三体')).response.status,401);assert.equal((await request('/api/uploads',{method:'POST',form:new FormData()})).response.status,401)});
 await check('original scrypt password authenticates and secure cookie is issued',async()=>{const result=await request('/api/auth/login',{method:'POST',data:{password:PASSWORD}});assert.equal(result.response.status,200);const value=result.response.headers.get('set-cookie');assert.match(value,/HttpOnly/);assert.match(value,/Secure/);assert.match(value,/SameSite=Strict/);cookie=value.split(';')[0];assert.equal((await request('/api/auth/status')).data.authenticated,true)});
 await check('phone pages and required modules load from asset binding',async()=>{for(const route of ['/','/admin?add=1','/book/seed-test','/ebook-ui.js','/book-lookup.js','/admin.css','/pulse-bridge.js']){const response=await request(route);assert.equal(response.response.status,200,route);assert.match(response.response.headers.get('x-content-type-options'),/nosniff/)}});
 await check('embedding permits the Pulse origin while retaining other browser protections',async()=>{const result=await request('/');const csp=result.response.headers.get('content-security-policy');assert.match(csp,/frame-ancestors 'self' https:\/\/codex-pulse-willow-0911\.wozhe0196\.chatgpt\.site;/);assert.match(csp,/object-src 'none'/);assert.equal(result.response.headers.get('x-frame-options'),null);assert.ok(!/frame-ancestors[^;]*\*/.test(csp))});
 const png=await readFile('public/assets/authors/author-1.jpg');let cover,file;
 await check('image and private TXT files stream into R2 with validated contents',async()=>{let form=new FormData();form.append('file',new File([png],'手机封面.jpg',{type:'image/jpeg'}));let result=await request('/api/uploads',{method:'POST',form});assert.equal(result.response.status,201,JSON.stringify(result.data));cover=result.data;form=new FormData();form.append('file',new File(['来自手机的个人电子书。'],'手机电子书.txt',{type:'text/plain'}));result=await request('/api/uploads',{method:'POST',form});assert.equal(result.response.status,201,JSON.stringify(result.data));file=result.data;assert.match(file.url,/^\/private-files\//)});
 await check('fake PDFs and unsupported files are rejected',async()=>{for(const name of ['fake.pdf','script.html']){const form=new FormData();form.append('file',new File(['fake content'],name));assert.equal((await request('/api/uploads',{method:'POST',form})).response.status,400)}});
 let book;
 await check('electronic links and phone attachment persist alongside private notes',async()=>{const data={title:'手机云端验收藏书',author:'测试作者',isbn:'9787536692930',publisher:'测试出版社',publishedDate:'2026',categoryId:'',coverUrl:cover.url,fileUrl:file.url,fileName:file.name,description:'公开简介',notes:'云端私人笔记',status:'reading',rating:4,ebookLinks:[link],featured:true};const result=await request('/api/books',{method:'POST',data});assert.equal(result.response.status,201,JSON.stringify(result.data));book=result.data;assert.deepEqual(book.ebookLinks,[link]);assert.equal((await request('/api/library')).data.books.find(b=>b.id===book.id).notes,'云端私人笔记')});
 await check('public library exposes links while protecting personal files and notes',async()=>{const value=(await request('/api/library',{auth:false})).data.books.find(b=>b.id===book.id);assert.equal(value.notes,undefined);assert.equal(value.fileUrl,undefined);assert.equal(value.hasFile,true);assert.deepEqual(value.ebookLinks,[link]);assert.equal((await request(`/api/books/${book.id}/file`,{auth:false})).response.status,401);assert.equal((await request(file.url)).response.status,404)});
 await check('uploaded cover decodes and authenticated attachment downloads',async()=>{const image=await request(cover.url,{auth:false});assert.equal(image.response.status,200);assert.match(image.response.headers.get('content-type'),/image\/jpeg/);const download=await request(`/api/books/${book.id}/file`);assert.equal(download.response.status,200);assert.equal(download.data,'来自手机的个人电子书。');assert.match(download.response.headers.get('content-disposition'),/filename\*=UTF-8/)});
 await check('metadata-only updates keep old electronic links and file association',async()=>{const result=await request(`/api/books/${book.id}`,{method:'PUT',data:{title:'修改标题'}});assert.equal(result.response.status,200);assert.equal(result.data.fileUrl,file.url);assert.deepEqual(result.data.ebookLinks,[link])});
 await check('invalid electronic URL is rejected before persistence',async()=>{const result=await request(`/api/books/${book.id}`,{method:'PUT',data:{ebookLinks:[{...link,url:'javascript:alert(1)'}]}});assert.equal(result.response.status,400);assert.deepEqual((await request('/api/library')).data.books.find(b=>b.id===book.id).ebookLinks,[link])});
 await check('cross-site writes are rejected',async()=>{assert.equal((await request('/api/settings',{method:'PUT',data:{title:'Attacker'},headers:{Origin:'https://example.com'}})).response.status,403)});
 await check('backup restore is atomic and includes links and notes',async()=>{const backup=(await request('/api/backup')).data;assert.equal(backup.books.find(b=>b.id===book.id).notes,'云端私人笔记');const invalid={...backup,books:[...backup.books,{title:'invalid id'}]};assert.equal((await request('/api/restore',{method:'POST',data:invalid})).response.status,400);assert.equal((await request('/api/library')).data.books.length,backup.books.length);assert.equal((await request('/api/restore',{method:'POST',data:backup})).response.status,200)});
 await check('migration accepts only its secret and is available once',async()=>{const backup=(await request('/api/backup')).data;assert.equal((await request('/api/bootstrap',{method:'POST',data:backup,headers:{'x-bookshelf-migration':'wrong'},auth:false})).response.status,403);assert.equal((await request('/api/bootstrap',{method:'POST',data:backup,headers:{'x-bookshelf-migration':migrationToken},auth:false})).response.status,200);assert.equal((await request('/api/bootstrap',{method:'POST',data:backup,headers:{'x-bookshelf-migration':migrationToken},auth:false})).response.status,403)});
 await check('changing password revokes the previous session',async()=>{const old=cookie;const result=await request('/api/auth/password',{method:'PUT',data:{currentPassword:PASSWORD,password:PASSWORD+' changed'}});assert.equal(result.response.status,200);cookie=result.response.headers.get('set-cookie').split(';')[0];assert.equal((await request('/api/auth/status',{headers:{Cookie:old}})).data.authenticated,false);assert.equal((await request('/api/auth/status')).data.authenticated,true)});
 await check('logout removes administrator access',async()=>{const result=await request('/api/auth/logout',{method:'POST',data:{}});assert.equal(result.response.status,200);assert.equal((await request('/api/auth/status')).data.authenticated,false)});
 console.log('Cloud workerd flows passed:',checks.length);
}catch(error){console.error(error);process.exitCode=1}finally{await mf?.dispose();await writeFile('../../work/cloud-smoke-results.json',JSON.stringify({passed:checks.length,checks},null,2))}
