import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomBytes,createCipheriv,createDecipheriv} from 'node:crypto';
import {GoogleTools,verificationCodes,windowsVaultCodec} from './google-tools.mjs';
import {resolveRelayRoute} from '../integration/local-apps/relay-policy.mjs';
import {AppsRelay,deriveRelayKey} from './apps-relay.mjs';
test('codes preserve leading zeros and do not treat phone numbers as verification codes',()=>{assert.deepEqual(verificationCodes('Your verification code is 001234. 验证码：765432'),['001234','765432']);assert.deepEqual(verificationCodes('Order 12345678, telephone 15018232559'),[]);assert.deepEqual(verificationCodes('verification code is 123456789'),[]);});
test('identity routes reject other hosts, arbitrary parameters and wrong verbs',()=>{assert.equal(resolveRelayRoute('GET','/relay/identity/gmail-codes?email=fixture%40gmail.com').app,'identity');for(const [method,url] of [['GET','/relay/identity/gmail-connection?email=fixture@gmail.com'],['POST','/relay/identity/status?email=fixture@gmail.com'],['GET','/relay/identity/status?email=fixture@attacker.invalid'],['GET','/relay/identity/status?email=fixture@gmail.com&email=other@gmail.com'],['GET','/relay/identity/status?email=fixture@gmail.com&host=attacker.invalid']])assert.equal(resolveRelayRoute(method,url),null);});
async function fixture(t,gmail){const root=await mkdtemp(path.join(os.tmpdir(),'pulse-google-test-')),key=randomBytes(32);const codec=async(op,data)=>{if(op==='protect'){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv),body=Buffer.concat([cipher.update(data),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]);}const decipher=createDecipheriv('aes-256-gcm',key,data.subarray(0,12));decipher.setAuthTag(data.subarray(12,28));return Buffer.concat([decipher.update(data.subarray(28)),decipher.final()]);};const tools=new GoogleTools(root,{codec,gmail}),server=http.createServer((req,res)=>tools.handle(req,res,new URL(req.url,'http://localhost')));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const request=(action,body)=>fetch(`http://127.0.0.1:${server.address().port}/relay/identity/${action}?email=fixture%40gmail.com`,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));assert.ok(path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(root).startsWith('pulse-google-test-'));await rm(root,{recursive:true,force:true});});return {tools,request,root,codec};}
test('credentials validate before saving, encrypted vault survives restart, and disconnect invalidates old reads',async t=>{
  let finish;const pending=new Promise(resolve=>finish=resolve),calls=[];
  const f=await fixture(t,async(email,password,read)=>{calls.push({email,password,read});if(password==='zzzzzzzzzzzzzzzz')throw new Error('do not leak synthetic password zzzzzzzzzzzzzzzz');return read?pending:[];});
  const bad=await f.request('gmail-connection',{action:'connect',password:'zzzzzzzzzzzzzzzz'});assert.equal(bad.status,401);assert.ok(!(await bad.text()).includes('zzzzzzzzzzzzzzzz'));assert.equal((await (await f.request('status')).json()).connected,false);
  const connected=await f.request('gmail-connection',{action:'connect',password:'abcdefghijklmnop'});assert.deepEqual(await connected.json(),{connected:true});assert.ok(!(await readFile(f.tools.file)).includes(Buffer.from('abcdefghijklmnop')));const restored=new GoogleTools(f.root,{codec:f.codec});assert.equal((await restored.load())['fixture@gmail.com'].password,'abcdefghijklmnop');
  const old=f.tools.codes('fixture@gmail.com');await new Promise(resolve=>setImmediate(resolve));assert.equal((await (await f.request('gmail-connection',{action:'disconnect'})).json()).connected,false);finish([{id:'fixture',codes:['001234']}]);assert.equal((await old).connected,false);assert.deepEqual((await old).messages,[]);assert.equal(f.tools.cache.has('fixture@gmail.com'),false);assert.equal(calls[0].read,false);
});
test('Windows DPAPI stores only encrypted bytes and decrypts under the same Windows user',async()=>{if(process.platform!=='win32')return;const clear=Buffer.from('synthetic fixture secret only'),encrypted=await windowsVaultCodec('protect',clear);assert.ok(!encrypted.includes(clear));assert.deepEqual(await windowsVaultCodec('unprotect',encrypted),clear);});
test('identity endpoint requires the relay key and does not retain passwords in operations receipts',async t=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'pulse-google-relay-test-')),token='synthetic-gateway-token-for-fixture';const relay=new AppsRelay(root,'',{disableTunnel:true,listenPort:0,deviceId:'12345678-1234-4234-8234-123456789012',readConfig:async()=>({ingestToken:token}),googleTools:{codec:async()=>{throw new Error('fixture never persists');},gmail:async()=>[]},createFinanceStorage:()=>({startImportServer:async()=>{},stop:async()=>{},handle:async()=>{}})});await relay.start();t.after(async()=>{await relay.stop();assert.ok(path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(root).startsWith('pulse-google-relay-test-'));await rm(root,{recursive:true,force:true});});const url=`http://127.0.0.1:${relay.port}/relay/identity/status?email=fixture%40gmail.com`;assert.equal((await fetch(url)).status,403);const response=await fetch(url,{headers:{'X-Pulse-Relay-Key':deriveRelayKey(token)}});assert.equal(response.status,200);assert.deepEqual(await response.json(),{connected:false,method:'app-password'});const write=await fetch(url.replace('/status?','/gmail-connection?'),{method:'POST',headers:{'X-Pulse-Relay-Key':deriveRelayKey(token),'Content-Type':'application/json'},body:JSON.stringify({action:'connect',password:'abcdefghijklmnop'})});assert.equal(write.status,503);assert.ok(!(await write.text()).includes('abcdefghijklmnop'));assert.equal(relay.db.prepare('SELECT COUNT(*) n FROM operations').get().n,0);
});
